SaffronCity_Mart_hns_MapScripts::
	.byte 0

SafronMart_EventScript_CooltrainerM::
	msgbox SaffronMart_Text_CooltrainerM, MSGBOX_NPC
	end
SafronMart_EventScript_CooltrainerF::
	msgbox SaffronMart_Text_CooltrainerF, MSGBOX_NPC
	end
SaffronMart_Text_CooltrainerM:
	.string "In LAVANDIA ist ein großer RADIOTURM.$"

SaffronMart_Text_CooltrainerF:
	.string "Ich möchte noch\n"
	.string "stärker werden, aber das bin ich noch\n"
	.string "nicht…\p"
	.string "Kannst du mir\n"
	.string "zeigen, wie man stärker wird?$"
