PewterCity_Mart_hns_MapScripts::
	.byte 0

PewterCity_Mart_EventScript_Youngster::
	msgbox PewterCity_Mart_Text_Youngster, MSGBOX_NPC
	end

PewterCity_Mart_EventScript_Nerd::
	msgbox PewterCity_Mart_Text_SuperNerd, MSGBOX_NPC
	end

PewterCity_Mart_Text_Youngster:
	.string "Hi! Mach doch\n"
	.string "Bekanntschaft mit meinem GARADOS!\p"
	.string "Ich habe es als\n"
	.string "KARPADOR aufgezogen. Kaum zu\p"
	.string "glauben, wie stark es geworden ist.$"

PewterCity_Mart_Text_SuperNerd:
	.string "Es gab mal einen\n"
	.string "komischen, alten Mann, der KARPADOR\n"
	.string "verkaufte.\p"
	.string "Er sagte immer, die KARPADOR im\p"
	.string "SEE DES ZORNS seien außergewöhnlich.$"

