.set LOCALID_LEAGUE_LANCE, 1
.set LOCALID_LEAGUE_MARY, 2
.set LOCALID_LEAGUE_OAK, 3

PokemonLeague_ChampionsRoom_hns_MapScripts::
	map_script MAP_SCRIPT_ON_FRAME_TABLE, ChampionRoom_OnFrame
	map_script MAP_SCRIPT_ON_RESUME, PokemonLeague_ChampionsRoom_OnResume
	.byte 0

PokemonLeague_ChampionsRoom_OnResume::
	setvar VAR_0x8004, 4
	special DoPokemonLeagueLightingEffect
	end

ChampionRoom_OnFrame::
	map_script_2 VAR_TEMP_0, 0, ChampionRoom_CloseDoor
	.2byte 0

ChampionRoom_CloseDoor::
	lock
	setflag FLAG_TEMP_2
	special DrawWholeMapView
	applymovement LOCALID_PLAYER, ChamionRoom_Movement_Enter
	waitmovement 0
	setvar VAR_TEMP_0, 1
	release
	end

ChamionRoom_Movement_Enter:
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

ChampionRoom_Trigger::
	lock
	applymovement LOCALID_PLAYER, Common_Movement_WalkUp
	waitmovement 0
	release
	end

PokemonLeague_WillsRoom_EventScript_Lance::
	lockall
	call_if_eq VAR_FACING, DIR_EAST, PokemonLeague_ChampionsRoom_EventScript_AdjustPlayerFacingEast
	call_if_eq VAR_FACING, DIR_SOUTH, PokemonLeague_ChampionsRoom_EventScript_AdjustPlayerFacingSouth
	call_if_eq VAR_FACING, DIR_WEST, PokemonLeague_ChampionsRoom_EventScript_AdjustPlayerFacingWest
	faceplayer
	goto_if_set FLAG_IS_CHAMPION, PokemonLeague_WillsRoom_EventScript_LanceRematch
	msgbox PokemonLeague_ChampionsRoom_Text_BattleIntro, MSGBOX_DEFAULT
	setflag FLAG_TEMP_3
	setflag FLAG_TEMP_5
	trainerbattle_no_intro TRAINER_LANCE_1, PokemonLeague_ChampionsRoom_Text_BattleWin
	goto PokemonLeague_WillsRoom_EventScript_LanceOnDefeatJohto

PokemonLeague_WillsRoom_EventScript_LanceRematch::
	msgbox PokemonLeague_ChampionsRoom_Text_RematchBattleIntro, MSGBOX_DEFAULT
	setflag FLAG_TEMP_3
	setflag FLAG_TEMP_5
	trainerbattle_no_intro TRAINER_LANCE_2, PokemonLeague_ChampionsRoom_Text_BattleWin
	goto PokemonLeague_WillsRoom_EventScript_LanceOnDefeatKanto

PokemonLeague_WillsRoom_EventScript_LanceOnDefeatJohto::
	clearflag FLAG_TEMP_5
	msgbox PokemonLeague_ChampionsRoom_Text_BattleAfter, MSGBOX_DEFAULT
	closemessage
	setmetatile 6, 1, 0x3F2, FALSE
	setmetatile 6, 2, 0x296, FALSE	
	playse SE_BANG
	setvar VAR_0x8004, 1  @ vertical pan
	setvar VAR_0x8005, 1  @ horizontal pan
	setvar VAR_0x8006, 4  @ num shakes
	setvar VAR_0x8007, 4  @ shake delay
	special ShakeCamera
	waitstate
	special DrawWholeMapView
	playse SE_PIN
	applymovement LOCALID_LEAGUE_LANCE, Common_Movement_ExclamationMark
	delay 40
	turnobject LOCALID_PLAYER, DIR_SOUTH
	applymovement LOCALID_PLAYER, PokemonLeague_ChampionsRoom_Movement_PlayerMoveToCenter
	applymovement LOCALID_LEAGUE_LANCE, PokemonLeague_ChampionsRoom_Movement_LanceMoveOver
	waitmovement LOCALID_PLAYER
	waitmovement LOCALID_LEAGUE_LANCE
	addobject LOCALID_LEAGUE_MARY
	addobject LOCALID_LEAGUE_OAK
	applymovement LOCALID_LEAGUE_MARY, PokemonLeague_ChampionsRoom_Movement_MaryEnter
	waitmovement 0
	msgbox PokemonLeague_ChampionsRoom_Text_MaryOhNoOak, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_LEAGUE_OAK, PokemonLeague_ChampionsRoom_Movement_OakEnter
	delay 60
	applymovement LOCALID_LEAGUE_MARY, PokemonLeague_ChampionsRoom_Movement_MaryMoveOver
	waitmovement LOCALID_LEAGUE_MARY
	waitmovement LOCALID_LEAGUE_OAK
	msgbox PokemonLeague_ChampionsRoom_Text_OakCongratulations, MSGBOX_DEFAULT
	applymovement LOCALID_LEAGUE_MARY, PokemonLeague_ChampionsRoom_Movement_MaryInterview
	waitmovement 0
	msgbox PokemonLeague_ChampionsRoom_Text_MaryInterview, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_LEAGUE_LANCE, PokemonLeague_ChampionsRoom_Movement_LanceAnxious
	waitmovement 0
	msgbox PokemonLeague_ChampionsRoom_Text_Noisy, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_LEAGUE_LANCE, PokemonLeague_ChampionsRoom_Movement_LanceLeave
	delay 30
	applymovement LOCALID_PLAYER, PokemonLeague_ChampionsRoom_Movement_PlayerLeave
	waitmovement LOCALID_LEAGUE_LANCE
	@setobjectxyperm LOCALID_LEAGUE_LANCE, 6, 14
	removeobject LOCALID_LEAGUE_LANCE
	playse SE_EXIT
	waitmovement LOCALID_PLAYER
	special SpawnCameraObject
	removeobject LOCALID_PLAYER
	playse SE_EXIT
	waitse
	delay 50
	applymovement LOCALID_LEAGUE_MARY, PokemonLeague_ChampionsRoom_Movement_MaryLeft
	waitmovement 0
	playse SE_PIN
	applymovement LOCALID_LEAGUE_MARY, Common_Movement_ExclamationMark
	delay 60
	msgbox PokemonLeague_ChampionsRoom_Text_MaryNoInterview, MSGBOX_DEFAULT
	closemessage
	setvar VAR_LEAGUE_STATE, 6
	warpsilent MAP_POKEMON_LEAGUE_HALL_OF_FAME, 0
	releaseall
	end

PokemonLeague_WillsRoom_EventScript_LanceOnDefeatKanto::
	clearflag FLAG_TEMP_5
	msgbox PokemonLeague_ChampionsRoom_Text_BattleAfter, MSGBOX_DEFAULT
	closemessage
	setmetatile 6, 1, 0x3F2, FALSE
	setmetatile 6, 2, 0x296, FALSE	
	playse SE_BANG
	setvar VAR_0x8004, 1  @ vertical pan
	setvar VAR_0x8005, 1  @ horizontal pan
	setvar VAR_0x8006, 4  @ num shakes
	setvar VAR_0x8007, 4  @ shake delay
	special ShakeCamera
	waitstate
	special DrawWholeMapView
	playse SE_PIN
	applymovement LOCALID_LEAGUE_LANCE, Common_Movement_ExclamationMark
	delay 40
	turnobject LOCALID_PLAYER, DIR_SOUTH
	applymovement LOCALID_PLAYER, PokemonLeague_ChampionsRoom_Movement_PlayerMoveToCenter
	applymovement LOCALID_LEAGUE_LANCE, PokemonLeague_ChampionsRoom_Movement_LanceMoveOver
	waitmovement LOCALID_PLAYER
	waitmovement LOCALID_LEAGUE_LANCE
	addobject LOCALID_LEAGUE_MARY
	addobject LOCALID_LEAGUE_OAK
	applymovement LOCALID_LEAGUE_MARY, PokemonLeague_ChampionsRoom_Movement_MaryEnter
	waitmovement 0
	msgbox PokemonLeague_ChampionsRoom_Text_MaryOhNoOak, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_LEAGUE_OAK, PokemonLeague_ChampionsRoom_Movement_OakEnter
	delay 60
	applymovement LOCALID_LEAGUE_MARY, PokemonLeague_ChampionsRoom_Movement_MaryMoveOver
	waitmovement LOCALID_LEAGUE_MARY
	waitmovement LOCALID_LEAGUE_OAK
	msgbox PokemonLeague_ChampionsRoom_Text_RematchOakCongratulations, MSGBOX_DEFAULT
	applymovement LOCALID_LEAGUE_MARY, PokemonLeague_ChampionsRoom_Movement_MaryInterview
	waitmovement 0
	msgbox PokemonLeague_ChampionsRoom_Text_RematchMaryInterview, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_LEAGUE_LANCE, PokemonLeague_ChampionsRoom_Movement_LanceAnxious
	waitmovement 0
	msgbox PokemonLeague_ChampionsRoom_Text_Noisy, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_LEAGUE_LANCE, PokemonLeague_ChampionsRoom_Movement_LanceLeave
	delay 30
	applymovement LOCALID_PLAYER, PokemonLeague_ChampionsRoom_Movement_PlayerLeave
	waitmovement LOCALID_LEAGUE_LANCE
	@setobjectxyperm LOCALID_LEAGUE_LANCE, 6, 14
	removeobject LOCALID_LEAGUE_LANCE
	playse SE_EXIT
	waitmovement LOCALID_PLAYER
	special SpawnCameraObject
	removeobject LOCALID_PLAYER
	playse SE_EXIT
	waitse
	delay 50
	applymovement LOCALID_LEAGUE_MARY, PokemonLeague_ChampionsRoom_Movement_MaryLeft
	waitmovement 0
	playse SE_PIN
	applymovement LOCALID_LEAGUE_MARY, Common_Movement_ExclamationMark
	delay 60
	msgbox PokemonLeague_ChampionsRoom_Text_RematchMaryNoInterview, MSGBOX_DEFAULT
	closemessage
	setvar VAR_LEAGUE_STATE, 6
	warpsilent MAP_POKEMON_LEAGUE_HALL_OF_FAME, 0
	releaseall
	end

PokemonLeague_ChampionsRoom_EventScript_AdjustPlayerFacingEast::
	applymovement LOCALID_PLAYER, PokemonLeague_ChampionsRoom_Movement_AdjustPlayerFacingEast
	waitmovement 0
	return
PokemonLeague_ChampionsRoom_EventScript_AdjustPlayerFacingSouth::
	applymovement LOCALID_PLAYER, PokemonLeague_ChampionsRoom_Movement_AdjustPlayerFacingSouth
	waitmovement 0
	return
PokemonLeague_ChampionsRoom_EventScript_AdjustPlayerFacingWest::
	applymovement LOCALID_PLAYER, PokemonLeague_ChampionsRoom_Movement_AdjustPlayerFacingWest
	waitmovement 0
	return

PokemonLeague_ChampionsRoom_Movement_AdjustPlayerFacingEast:
	walk_down
	walk_right
	face_up
	step_end
PokemonLeague_ChampionsRoom_Movement_AdjustPlayerFacingSouth:
	walk_left
	walk_down
	walk_down
	walk_right
	face_up
	step_end
PokemonLeague_ChampionsRoom_Movement_AdjustPlayerFacingWest:
	walk_down
	walk_left
	face_up
	step_end

PokemonLeague_ChampionsRoom_Movement_PlayerMoveToCenter:
	lock_facing_direction
	walk_up
	unlock_facing_direction
	step_end

PokemonLeague_ChampionsRoom_Movement_LanceMoveOver:
	lock_facing_direction
	walk_right
	unlock_facing_direction
	step_end

PokemonLeague_ChampionsRoom_Movement_MaryEnter:
	walk_fast_up
	walk_fast_up
	walk_fast_up
	walk_fast_up
	walk_fast_up
	walk_fast_up
	delay_2
	walk_in_place_fast_down
	step_end

PokemonLeague_ChampionsRoom_Movement_MaryMoveOver:
	walk_left
	face_right
	step_end

PokemonLeague_ChampionsRoom_Movement_OakEnter:
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

PokemonLeague_ChampionsRoom_Movement_MaryInterview:
	walk_fast_up
	walk_in_place_fast_right
	step_end

PokemonLeague_ChampionsRoom_Movement_LanceAnxious:
	face_up
	delay_16
	delay_16
	face_down
	delay_16
	delay_16
	face_left
	step_end

PokemonLeague_ChampionsRoom_Movement_LanceLeave:
	walk_up
	walk_left
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

PokemonLeague_ChampionsRoom_Movement_PlayerLeave:
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

PokemonLeague_ChampionsRoom_Movement_MaryLeft:
	walk_fast_right
	walk_fast_up
	walk_fast_up
	walk_fast_up
	walk_fast_up
	step_end

PokemonLeague_ChampionsRoom_Text_RematchBattleIntro:
	.string "Siegfried: Willkommen zurück!\p"
	.string "Du hast dich in JOHTO bewährt\p"
	.string "und alle 8 Orden errungen,\p"
	.string "sogar mich einst besiegt.\p"
	.string "Doch jetzt spielst du ganz oben.\p"
	.string "In der großen Liga.\p"
	.string "Der KANTO-LIGA!\p"
	.string "Eine Region mit eigenen Prüfungen\n"
	.string "und Champions.\p"
	.string "Hier bin ich die letzte Hürde,\p"
	.string "mit einem Team stärker als je\n"
	.string "zuvor.\p"
	.string "Dies ist die wahre Prüfung,\p"
	.string "der Kampf um den Titel des\p"
	.string "KANTO-CHAMPIONS.\p"
	.string "Bist du bereit für diese neue\p"
	.string "Herausforderung?\p"
	.string "Willst du dich erneut beweisen?\p"
	.string "Zeig mir die Stärke,\p"
	.string "die JOHTO erobert hat,\p"
	.string "CHAMPION.$"

PokemonLeague_ChampionsRoom_Text_BattleIntro:
	.string "Siegfried: Ich habe auf dich\p"
	.string "gewartet.\p"
	.string "{PLAYER}!\p"
	.string "Ich wusste, dass du mit deinem\p"
	.string "Können eines Tages hier stehst.\p"
	.string "Jetzt braucht es keine Worte.\p"
	.string "Wir kämpfen um zu sehen,\p"
	.string "wer von uns der Stärkere ist.\p"
	.string "Als mächtigster Trainer und\p"
	.string "als CHAMPION der POKéMON-LIGA…\p"
	.string "ich, Siegfried, der Drachenmeister,\p"
	.string "nehme deine Herausforderung an!$"

PokemonLeague_ChampionsRoom_Text_BattleWin:
	.string "…Es ist vorbei.\p"
	.string "Doch es fühlt sich seltsam an.\p"
	.string "Ich bin nicht wütend über die\p"
	.string "Niederlage.\p"
	.string "Im Gegenteil, ich bin froh.\p"
	.string "Froh, den Aufstieg eines neuen\p"
	.string "großen CHAMPIONS gesehen zu haben!$"

PokemonLeague_ChampionsRoom_Text_BattleAfter:
	.string "…Puh.\p"
	.string "Du bist wirklich stark geworden,\p"
	.string "{PLAYER}.\p"
	.string "Deine Pokémon reagieren auf deine\p"
	.string "aufrechte und starke Art.\p"
	.string "Als Trainer wirst du gemeinsam\p"
	.string "mit deinen Pokémon weiter wachsen.$"

PokemonLeague_ChampionsRoom_Text_MaryOhNoOak:
	.string "Margit: Oh nein! Es ist vorbei!\p"
	.string "PROF. Eich, wärst du nicht so langsam…$"

PokemonLeague_ChampionsRoom_Text_OakCongratulations:
	.string "PROF. Eich: Ah, {PLAYER}!\p"
	.string "Es ist lange her.\p"
	.string "Du wirkst sehr beeindruckend.\p"
	.string "Dein Sieg in der JOHTO-LIGA\p"
	.string "ist wirklich fantastisch!\p"
	.string "Dein Einsatz, Vertrauen und\p"
	.string "deine Liebe zu Pokémon\p"
	.string "haben das möglich gemacht.\p"
	.string "Auch deine Pokémon waren großartig.\p"
	.string "Sie glaubten an dich als Trainer\p"
	.string "und hielten durch.\p"
	.string "Herzlichen Glückwunsch,\p"
	.string "{PLAYER}!$"

PokemonLeague_ChampionsRoom_Text_RematchOakCongratulations:
	.string "PROF. Eich: Ah, {PLAYER}!\p"
	.string "Ich habe deinen Weg verfolgt,\p"
	.string "seit PROF. LIND dich losschickte.\p"
	.string "Du bist noch beeindruckender\p"
	.string "geworden.\p"
	.string "JOHTO und nun auch KANTO zu\p"
	.string "bezwingen ist keine Kleinigkeit.\p"
	.string "Du hast dich selbst übertroffen!\p"
	.string "Deine Pokémon vertrauen dir sehr,\p"
	.string "und dieses Vertrauen ist die\p"
	.string "Grundlage deines Erfolgs.\p"
	.string "Doch vergiss nie:\p"
	.string "Die Reise eines Trainers endet nie.\p"
	.string "Wenn du Zeit hast, besuche mich\p"
	.string "in meinem Labor.\p"
	.string "Ich möchte etwas mit dir\p"
	.string "besprechen.\p"
	.string "Glückwunsch zu deinem Sieg,\p"
	.string "{PLAYER}!$"

PokemonLeague_ChampionsRoom_Text_MaryInterview:
	.string "Margit: Interview mit dem neuen\p"
	.string "JOHTO-CHAMPION!$"

PokemonLeague_ChampionsRoom_Text_RematchMaryInterview:
	.string "Margit: Interview mit dem neuen\p"
	.string "KANTO-CHAMPION!$"

PokemonLeague_ChampionsRoom_Text_Noisy:
	.string "Siegfried: Es wird mir etwas\p"
	.string "zu laut…\p"
	.string "{PLAYER}, komm bitte mit mir.$"

PokemonLeague_ChampionsRoom_Text_MaryNoInterview:
	.string "Margit: Moment! Das Interview\p"
	.string "fehlt noch!$"

PokemonLeague_ChampionsRoom_Text_RematchMaryNoInterview:
	.string "Margit: Hey! Du kannst das\p"
	.string "Interview nicht schon wieder\p"
	.string "sausen lassen!$"

