ViridianCity_hns_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, ViridianCity_EventScript_CityEnter
	.byte 0

ViridianCity_EventScript_CityEnter::
	setflag FLAG_VISITED_VIRIDIAN_CITY
	end

ViridianCity_EventScript_Gramps::
	lock
	faceplayer
	msgbox ViridianCity_Text_CoffeeGramps_Question, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, FALSE, ViridianCity_EventScript_GrampsDoubted
	msgbox ViridianCity_Text_CoffeeGramps_Believed, MSGBOX_DEFAULT
	closemessage
	release
	end

ViridianCity_EventScript_GrampsDoubted::
	msgbox ViridianCity_Text_CoffeeGramps_Doubted, MSGBOX_DEFAULT
	closemessage
	release
	end

VirianCity_EventScript_GymGramps::
	goto_if_set FLAG_HIDE_CINNABAR_BLUE, VirianCity_EventScript_GymGrampsBlue
	msgbox ViridianCity_Text_GrampsNearGym, MSGBOX_NPC
	end

VirianCity_EventScript_GymGrampsBlue::
	msgbox ViridianCity_Text_GrampsNearGym_BlueReturned, MSGBOX_NPC
	end

ViridianCity_EventScript_Fisher::
	goto_if_set FLAG_GOT_VIRIDIAN_TM_SLUDGE_BOMB, ViridianCity_EventScript_FisherAfter
	msgbox ViridianCity_Text_DreamEaterFisherNew, MSGBOX_NPC
	giveitem ITEM_TM_SLUDGE_BOMB
	setflag FLAG_GOT_VIRIDIAN_TM_SLUDGE_BOMB
	end

ViridianCity_EventScript_FisherAfter::
	msgbox ViridianCity_Text_DreamEaterFisher_GotTM, MSGBOX_NPC
	end

ViridianCity_EventScript_Youngster::
	msgbox ViridianCity_Text_Youngster, MSGBOX_NPC
	end

ViridianCity_EventScript_CitySign::
	msgbox ViridianCity_Text_WelcomeSign, MSGBOX_SIGN
	end

ViridianCity_EventScript_CitySign2::
	msgbox ViridianCity_Text_Sign, MSGBOX_SIGN
	end

ViridianCity_EventScript_GymSign::
	msgbox ViridianCity_Text_GymSign, MSGBOX_SIGN
	end

ViridianCity_Text_CoffeeGramps_Question:
	.string "He, Kurzbein! Ich hatte gerade einen\p"
	.string "doppelten Espresso\n"
	.string "und ich bin total aufgedreht!\p"
	.string "Ich brauche jetzt\n"
	.string "jemanden zum Reden und zwar dich!\p"
	.string "Man sieht es mir jetzt vielleicht\p"
	.string "nicht mehr an,\n"
	.string "aber ich war ein Experte im Fangen von\n"
	.string "Pokémon.\p"
	.string "Glaubst du mir?$"

ViridianCity_Text_CoffeeGramps_Believed:
	.string "Also gut. Ja, ich war wirklich etwas\p"
	.string "Besonderes, das kann ich dir sagen!$"

ViridianCity_Text_CoffeeGramps_Doubted:
	.string "Was? Du kleiner Frechdachs!\p"
	.string "Wenn ich etwas jünger wäre, würde\p"
	.string "ich dir schon das\n"
	.string "eine oder andere zeigen! Grummel.$"

ViridianCity_Text_GrampsNearGym:
	.string "Bis vor kurzem\n"
	.string "gab es in dieser PKMN-ARENA keinen\n"
	.string "LEITER.\p"
	.string "Ein junger Mann aus ALABASTIA ist\p"
	.string "hier der LEITER\n"
	.string "geworden, aber er ist oft unterwegs.$"

ViridianCity_Text_GrampsNearGym_BlueReturned:
	.string "Wirst du den\n"
	.string "ARENALEITER herausfordern?\p"
	.string "Viel Glück! Du wirst es brauchen.$"

ViridianCity_Text_DreamEaterFisherNew:
	.string "Gähn!\p"
	.string "Ich bin wohl in\n"
	.string "der Sonne eingeschlafen.\p"
	.string "…Ich hatte diesen Traum von einem\p"
	.string "TRAUMATO, das meinen Traum\p"
	.string "fressen wollte. Das ist doch\p"
	.string "merkwürdig, nicht wahr?\p"
	.string "Nanu! Was ist das?\p"
	.string "Wo ist diese TM hergekommen?\p"
	.string "Unheimlich!\n"
	.string "Hier, du kannst die TM behalten.$"


ViridianCity_Text_DreamEaterFisher_GotTM::
	.string "…Zzzzz…$"

ViridianCity_Text_DreamEaterFisher:
	.string "Gähn!\p"
	.string "Ich bin wohl in\n"
	.string "der Sonne eingeschlafen.\p"
	.string "…Ich hatte diesen Traum von einem\p"
	.string "TRAUMATO, das meinen Traum\p"
	.string "fressen wollte. Das ist doch\p"
	.string "merkwürdig, nicht wahr?\p"
	.string "Nanu! Was ist das?\p"
	.string "Wo ist diese TM hergekommen?\p"
	.string "Unheimlich!\n"
	.string "Hier, du kannst die TM behalten.$"

ViridianCity_Text_DreamEaterFisher_GotDreamEater:
	.string "TM42 enthält TRAUMFRESSER…\p"
	.string "…Zzzzz…$"

ViridianCity_Text_Youngster:
	.string "Ich habe gehört, dass man viele\p"
	.string "Items im VERTANIAWALD findet.$"

ViridianCity_Text_Sign:
	.string "VERTANIA CITY\p"
	.string "Das Immergrüne Paradies$"

ViridianCity_Text_GymSign:
	.string "VERTANIA CITY\p"
	.string "Das Immergrüne Paradies$"

ViridianCity_Text_WelcomeSign:
	.string "Willkommen in VERTANIA CITY,\p"
	.string "dem Tor zum INDIGO PLATEAU$"

ViridianCity_Text_TrainerHouseSign:
	.string "TRAINER HAUS\p"
	.string "Der Verein für Top Trainerkämpfe$"
