gText_Birch_Welcome::
	.string "Entschuldige das du warten musstest.\p"
	.string "Willkommen in der Welt der POKéMON!\p"
	.string "Mein Name ist EICH.\p"
	.string "Aber jeder nennt mich nur\n"
	.string "PROFESSOR POKéMON.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Das hier nennen wir “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Auf dieser Welt leben Wesen,\n"
	.string "die uns als POKéMON bekannt sind.\p"
	.string "Wir Menschen leben Seite an Seite\n"
	.string "mit ihnen, als Freunde oder als\l"
	.string "Arbeitskollegen.\p"
	.string "Und manchmal schließen wir uns mit\n"
	.string "ihnen zusammen und tragen Kämpfe\l"
	.string "gegen andere von uns aus.\p"
	.string "Doch obwohl wir den POKéMON so\n"
	.string "nahe stehen, wissen wir noch nicht\l"
	.string "alles über sie.\p"
	.string "Es gibt noch viele, viele Geheim-\n"
	.string "nisse um die POKéMON.\p"
	.string "Um die Mysterien der POKéMON\n"
	.string "aufzudecken, widme ich mich der\l"
	.string "Forschung. Genau das tue ich.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Und wer bist du?$"

gText_Birch_BoyOrGirl::
	.string "Bist du ein Junge?\n"
	.string "Oder bist du ein Mädchen?$"

gText_Birch_Difficulty::
	.string "Aha…\p"
	.string "Und… wie denkst du,\n"
	.string "wird das Abenteuer werden?$"

gText_Birch_LockDifficulty::
	.string "Falls du die Schwierigkeit ändern\n"
	.string "möchtest, öffne die OPTIONEN\l"
	.string "und ändere sie dort.\p"
	.string "Du kannst sie auch festsetzen.\n"
	.string "Möchtest du die Schwierigkeit\l"
	.string "unveränderbar machen?\p"
	.string "Das kann später nicht geändert werden.$"

gText_Birch_Challenge::
	.string "Oh, ist das so?\p"
	.string "Na gut, alles klar…\n"
	.string "Denkst du es wird CHALLENGES\l"
	.string "auf deiner Reise geben?\p"
	.string "Und wie heißt du?$"

gText_Birch_WhatsYourName::
	.string "Fein!\n"
	.string "Und wie heißt du?$"

gText_Birch_SoItsPlayer::
	.string "Ah, du bist also {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "Jetzt habe ich es! Du heißt {PLAYER}{KUN}\n"
	.string "und bist gerade nach NEUBORKIA,\l"
	.string "gezogen, schöner Ort.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Gut, bist du bereit?\p"
	.string "Dein eigenes Abenteuer wird\n"
	.string "nun beginnen.\p"
	.string "Hab nur Mut und stürze dich in die\n"
	.string "Welt der POKéMON, wo Abenteuer,\l"
	.string "Träume und Freundschaft warten.\p"
	.string "Komm später in mein POKéMON-LABOR,\n"
	.string "ich erwarte dich dort.\p"
	.string "$"

