@ Battle Tower
gText_AnabelWonSilver::
	.string "Das ist sehr enttäuschend…$"

gText_AnabelDefeatSilver::
	.string "Okay, ich verstehe…$"

gText_AnabelWonGold::
	.string "Es tut mir schrecklich leid…$"

gText_AnabelDefeatGold::
	.string "Danke…$"

@ Battle Dome
gText_TuckerWonSilver::
	.string "Ahahaha! Ist dir das nicht peinlich?\n"
	.string "Alle schauen zu!$"

gText_TuckerDefeatSilver::
	.string "Grr…\n"
	.string "Was zum…$"

gText_TuckerWonGold::
	.string "Mein DOME-ACE-Titel ist kein Scherz!$"

gText_TuckerDefeatGold::
	.string "Ahahaha!\n"
	.string "Du bist inspirierend!$"

@ Battle Factory
gText_NolandWonSilver::
	.string "Gut gemacht!\n"
	.string "Das war eine gute Lektion, hm?$"

gText_NolandDefeatSilver::
	.string "Gut gemacht!\n"
	.string "Du weißt, was du tust!$"

gText_NolandWonGold::
	.string "Hey, hey, hey!\n"
	.string "Schon fertig damit?$"

gText_NolandDefeatGold::
	.string "Was ist hier passiert?$"

@ Battle Pike
gText_LucyWonSilver::
	.string "Humph…$"

gText_LucyDefeatSilver::
	.string "Urk…$"

gText_LucyWonGold::
	.string "Hah!$"

gText_LucyDefeatGold::
	.string "Verdammt!$"

@ Battle Arena
gText_GretaWonSilver::
	.string "Ach, komm schon!\n"
	.string "Du musst dich mehr anstrengen!$"

gText_GretaDefeatSilver::
	.string "Nein!\n"
	.string "Gut gemacht!$"

gText_GretaWonGold::
	.string "Heheh!\n"
	.string "Was hast du erwartet?$"

gText_GretaDefeatGold::
	.string "Häh?\n"
	.string "Meinst du das ernst?!$"

@ Battle Palace
gText_SpenserWonSilver::
	.string "Deine POKéMON sind schwach,\n"
	.string "weil du als TRAINER schwach bist!$"

gText_SpenserDefeatSilver::
	.string "Ah…\n"
	.string "Das ist was anderes…$"

gText_SpenserWonGold::
	.string "Gwahahaha!\n"
	.string "Brüder, wir haben nichts zu fürchten!$"

gText_SpenserDefeatGold::
	.string "Gwah!\n"
	.string "Hahahaha!$"

@ Battle Pyramid
gText_BrandonWonSilver::
	.string "Hey! Was stimmt mit dir?\n"
	.string "Zeig Einsatz! Aufstehen!$"

gText_BrandonDefeatSilver::
	.string "Das war's! Gut gemacht!\n"
	.string "Du hast hart dafür gearbeitet!$"

gText_BrandonWonGold::
	.string "Hey! Jetzt nicht aufgeben!\n"
	.string "Aufstehen! Verlier nie den Mut!$"

gText_BrandonDefeatGold::
	.string "Das war's! Du hast es geschafft!\n"
	.string "Du hast hart dafür gearbeitet!$"
