MoveRelearner_Text_WouldLearnNewMoves:
	.string "Hi, ich bin der Attacken Erlerner.\n"
	.string "Möchtest du Attacken lernen?$"

MoveRelearner_Text_LevelUpMoves:
	.string "Level Up Attacken$"

MoveRelearner_Text_EggMoves:
	.string "Ei Attacken$"

MoveRelearner_Text_TMMoves:
	.string "TM Attacken$"

MoveRelearner_Text_TutormoveMoves:
	.string "Lehrer Attacken$"

MoveRelearner_Text_SeeYa:
	.string "Tschüss!$"

MoveRelearner_Text_AnythingElse:
	.string "Kann ich sonst noch etwas tun?$"

MoveRelearner_Text_ChoosePkmn:
	.string "Bitte wähle dein Pokémon.$"

MoveRelearner_Text_HaveNoPkmn:
	.string "Du hast kein Pokémon.$"

MoveRelearner_Text_CantTeachMoveToEgg:
	.string "Sorry…\n"
	.string "Ein Ei kann nichts lernen.$"

MoveRelearner_Text_CantTeachMoveToPkmn:
	.string "Sorry…\p"
	.string "Ich habe keine Attacken\n"
	.string "für dieses Pokémon.$"

MoveRelearner_Text_LevelUpMoveLWR::
	.string "level up attacke$"

MoveRelearner_Text_EggMoveLWR::
	.string "ei attacke$"

MoveRelearner_Text_TMMoveLWR::
	.string "TM attacke$"

MoveRelearner_Text_TutorMoveLWR::
	.string "lehrer attacke$"

MoveRelearner_Text_WhichXmoveShouldTeach:
	.string "Welche {STR_VAR_3} soll ich lehren?$"

MoveRelearner_Text_ThankYouComeAgain:
	.string "Vielen Dank!\n"
	.string "Bitte komm doch wieder!$"
