Text_BootUpPC:
	.string "{PLAYER} schaltet den PC ein.$"

gText_WhichPCShouldBeAccessed::
	.string "Zugriff auf wessen PC?$"

gText_AccessedSomeonesPC::
	.string "Verbindung zu JEMANDES PC hergestellt.$"

gText_StorageSystemOpened::
	.string "POKéMON-Lagerungs-System geöffnet.$"

gText_AccessedPlayersPC::
	.string "Verbindung mit PC von {PLAYER}.$"

gText_AccessedBillsPC::
	.string "Verbindung zu BILL'S PC hergestellt.$"
