gText_PkmnTransferredSomeonesPC::
	.string "{STR_VAR_2} wurde auf JEMANDES PC\n"
	.string "übertragen.\p"
	.string "Es wurde in BOX\n"
	.string "“{STR_VAR_1}” abgelegt.$"

gText_PkmnTransferredBillsPC::
	.string "{STR_VAR_2} wurde auf BILL'S PC.\n"
	.string "übertragen.\p"
	.string "Es wurde in BOX\n"
	.string "“{STR_VAR_1}” abgelegt.$"

gText_PkmnTransferredSomeonesPCBoxFull::
	.string "BOX “{STR_VAR_3}” in\n"
	.string "JEMANDES PC ist voll.\p"
	.string "{STR_VAR_2} wurde in BOX\n"
	.string "“{STR_VAR_1}” übertragen.$"

gText_PkmnTransferredBillsPCBoxFull::
	.string "BOX “{STR_VAR_3}” in\n"
	.string "BILL'S PC ist voll.\p"
	.string "{STR_VAR_2} wurde in BOX\n"
	.string "“{STR_VAR_1}” übertragen.$"

gText_PkmnSentToPCAfterCatch::
	.string "{STR_VAR_2} wurde zu\n"
	.string "{B_PC_CREATOR_NAME} PC.\p"
	.string "gesendet in \n"
	.string "BOX “{STR_VAR_1}”.$"
	
gText_PkmnSentToSomeonesPCAfterCatch::
	.string "{STR_VAR_2} wurde zu\n"
	.string "JEMANDES PC.\p"
	.string "gesendet in \n"
	.string "BOX “{STR_VAR_1}”.$"

gText_PkmnSentToBillsPCAfterCatch::
	.string "{STR_VAR_2} wurde zu\n"
	.string "BILL'S PC.\p"
	.string "gesendet in \n"
	.string "BOX “{STR_VAR_1}”.$"

gText_NoMoreRoomForPokemon::
	.string "Es ist kein Platz mehr für POKéMON\n"
	.string "vorhanden!\p"
	.string "Die POKéMON BOXen sind voll und\n"
	.string "es kann kein POKéMON mehr\l"
	.string "abgelegt werden!$"

gText_NicknameThisPokemon::
	.string "Möchtest du {STR_VAR_1} einen\n"
	.string "Spitznamen geben?$"
