gTrickHouse_Mechadoll_Oddish::
	.string "MYRAPLA$"

gTrickHouse_Mechadoll_Poochyena::
	.string "FIFFYEN$"

gTrickHouse_Mechadoll_Taillow::
	.string "SCHWALBINI$"

gTrickHouse_Mechadoll_Azurill::
	.string "AZURILL$"

gTrickHouse_Mechadoll_Lotad::
	.string "LOTURZEL$"

gTrickHouse_Mechadoll_Wingull::
	.string "WINGULL$"

gTrickHouse_Mechadoll_Dustox::
	.string "PUDOX$"

gTrickHouse_Mechadoll_Zubat::
	.string "ZUBAT$"

gTrickHouse_Mechadoll_Nincada::
	.string "NINCADA$"

gTrickHouse_Mechadoll_Ralts::
	.string "TRASLA$"

gTrickHouse_Mechadoll_Zigzagoon::
	.string "ZIGZACHS$"

gTrickHouse_Mechadoll_Slakoth::
	.string "BUMMELZ$"

gTrickHouse_Mechadoll_Poochyena2::
	.string "FIFFYEN$"

gTrickHouse_Mechadoll_Shroomish::
	.string "KNILZ$"

gTrickHouse_Mechadoll_Zigzagoon2::
	.string "ZIGZACHS$"

gTrickHouse_Mechadoll_Poochyena3::
	.string "FIFFYEN$"

gTrickHouse_Mechadoll_Zubat2::
	.string "ZUBAT$"

gTrickHouse_Mechadoll_Carvanha::
	.string "CARVANHA$"

gTrickHouse_Mechadoll_BurnHeal::
	.string "FEUERHEILER$"

gTrickHouse_Mechadoll_HarborMail::
	.string "HAFENBRIEF$"

gTrickHouse_Mechadoll_SamePrice::
	.string "Same price$"

gTrickHouse_Mechadoll_60Yen::
	.string "¥60$"

gTrickHouse_Mechadoll_55Yen::
	.string "¥55$"

gTrickHouse_Mechadoll_Nothing::
	.string "Nichts$"

gTrickHouse_Mechadoll_CostMore::
	.string "Sie kosten mehr.$"

gTrickHouse_Mechadoll_CostLess::
	.string "Sie kosten weniger.$"

gTrickHouse_Mechadoll_SamePrice2::
	.string "Gleicher Preis$"

gTrickHouse_Mechadoll_Male::
	.string "Männlich$"

gTrickHouse_Mechadoll_Female::
	.string "Weiblich$"

gTrickHouse_Mechadoll_Neither::
	.string "Keinen$"

gTrickHouse_Mechadoll_ElderlyMen::
	.string "Alte Männer$"

gTrickHouse_Mechadoll_ElderlyLadies::
	.string "Alte Frauen$"

gTrickHouse_Mechadoll_SameNumber::
	.string "Gleiche Nummer$"

gTrickHouse_Mechadoll_None::
	.string "Nichts$"

gTrickHouse_Mechadoll_One::
	.string "1$"

gTrickHouse_Mechadoll_Two::
	.string "2$"

gTrickHouse_Mechadoll_Two2::
	.string "2$"

gTrickHouse_Mechadoll_Three::
	.string "3$"

gTrickHouse_Mechadoll_Four::
	.string "4$"

gTrickHouse_Mechadoll_Six::
	.string "6$"

gTrickHouse_Mechadoll_Seven::
	.string "7$"

gTrickHouse_Mechadoll_Eight::
	.string "8$"

gTrickHouse_Mechadoll_Six2::
	.string "6$"

gTrickHouse_Mechadoll_Seven2::
	.string "7$"

gTrickHouse_Mechadoll_Eight2::
	.string "8$"
