FuchsiaCity_House1_hns_MapScripts::
	.byte 0

FuchsiaCity_House1_EventScript_BillsOlderSister::
	msgbox FuchsiaCity_House1_Text_BillsOlderSister, MSGBOX_NPC
	end

FuchsiaCity_House1_EventScript_Youngster::
	msgbox FuchsiaCity_House1_Text_Youngster, MSGBOX_NPC
	end

FuchsiaCity_House1_Text_BillsOlderSister:
	.string "Mein Opa ist bei meinem Bruder Bill\n"
	.string "beim Kap Azuria.$"

FuchsiaCity_House1_Text_Youngster:
	.string "Ich habe diese komischen, langsamen\p"
	.string "Pokémon auf dem Radweg gesehen.$"

