Route40_hns_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, OlivineCity_MapScript_OnTransition
	.byte 0

Route40_EventScript_Simon::
	trainerbattle_single TRAINER_SIMON, Route40_Text_SwimmermSimonSeen, Route40_Text_SwimmermSimonBeaten
	msgbox Route40_Text_SwimmermSimonAfter, MSGBOX_AUTOCLOSE
	end

Route40_Text_SwimmermSimonSeen:
	.string "Du musst dich erst\n"
	.string "aufwärmen, bevor du schwimmen gehst.\p"
	.string "Das ist Grundwissen.$"

Route40_Text_SwimmermSimonBeaten:
	.string "O.K.! Onkel! Ich gebe auf!$"

Route40_Text_SwimmermSimonAfter:
	.string "Anemonia City ist ziemlich\n"
	.string "weit weg von hier.$"

Route40_EventScript_Randall::
	trainerbattle_single TRAINER_RANDALL, Route40_Text_SwimmermRandallSeen, Route40_Text_SwimmermRandallBeaten
	msgbox Route40_Text_SwimmermRandallAfter, MSGBOX_AUTOCLOSE
	end

Route40_Text_SwimmermRandallSeen:
	.string "Heh, du bist jung und fit!\p"
	.string "Surfe nicht auf\n"
	.string "deinem Pokémon! Schwimme!$"

Route40_Text_SwimmermRandallBeaten:
	.string "Oh, oh. Ich habe verloren…$"

Route40_Text_SwimmermRandallAfter:
	.string "Schwimmen ist gut für\n"
	.string "deinen gesamten Körper.$"

Route40_EventScript_Elaine::
	trainerbattle_single TRAINER_ELAINE, Route40_Text_SwimmerfElaineSeen, Route40_Text_SwimmerfElaineBeaten
	msgbox Route40_Text_SwimmerfElaineAfter, MSGBOX_AUTOCLOSE
	end

Route40_Text_SwimmerfElaineSeen:
	.string "Gehst du nach ANEMONIA CITY?\p"
	.string "Wie wäre es erst\n"
	.string "mit einem kleinen Kampftraining?$"

Route40_Text_SwimmerfElaineBeaten:
	.string "Diesmal habe ich verloren!$"

Route40_Text_SwimmerfElaineAfter:
	.string "Ich denke ich bin ein besserer\n"
	.string "Schwimmer als du. Yeah!$"

Route40_EventScript_Paula::
	trainerbattle_single TRAINER_PAULA, Route40_Text_SwimmerfPaulaSeen, Route40_Text_SwimmerfPaulaBeaten
	msgbox Route40_Text_SwimmerfPaulaAfter, MSGBOX_AUTOCLOSE
	end

Route40_Text_SwimmerfPaulaSeen:
	.string "Ich habe keine Schwimmreifen.\p"
	.string "Ich halte mich an\n"
	.string "einem WasserPokémon fest!$"

Route40_Text_SwimmerfPaulaBeaten:
	.string "Oh, ich fühle mich so schwindelig!$"

Route40_Text_SwimmerfPaulaAfter:
	.string "Ich gleite unbeschwert\n"
	.string "über die Wellen.$"

Route40_EventScript_Woman1::
	lock
	faceplayer
	msgbox Route40_Text_Lass1, MSGBOX_DEFAULT
	closemessage
	release
	end

Route40_Text_Lass1:
	.string "Du kannst es zwar nicht von hier\p"
	.string "sehen, aber ANEMO-\n"
	.string "NIA CITY liegt jenseits des Meeres.$"

Route40_EventScript_Woman2::
	lock
	faceplayer
	msgbox Route40_Text_Lass2, MSGBOX_DEFAULT
	closemessage
	release
	end

Route40_Text_Lass2:
	.string "Ich reiste mit dem Schiff nach\p"
	.string "OLIVIANA, um die Sehenswürdigkeiten\p"
	.string "und die Atmosphäre zu genießen.\p"
	.string "Da es eine Hafenstadt ist, unter-\p"
	.string "scheidet sie sich\n"
	.string "von anderen großen Städten.$"

Route40_EventScript_Youngster::
	lock
	faceplayer
	msgbox Route40_Text_StandingYoungster, MSGBOX_DEFAULT
	closemessage
	release
	end

Route40_Text_StandingYoungster:
	.string "Warst du schon am DUELLTURM?\p"
	.string "Ich denke, dass sich bereits viele\p"
	.string "starke Trainer dort versammeln.\p"
	.string "Da du so viele ORDEN besitzt,\p"
	.string "wirst du dich dort wacker schlagen.$"

Route40_Text_Monica::
	.string "Monja: Schön, dich zu treffen.\n"
	.string "Ich bin Monja von der WOCHENFAMILIE.\p"
	.string "Ich wette, du kannst nicht\n"
	.string "erraten, welcher mein Lieblingstag\l"
	.string "ist!$"

Route40_Text_MonicaGivesGift::
	.string "Als Zeichen\n"
	.string "unserer Freundschaft schenke ich dir\l"
	.string "dies!$"

Route40_Text_MonicaGaveGift::
	.string "Monja: Das ist ein Item, das die\n"
	.string "Kraft von Flug-Attacken\n"
	.string "erhöht.\p"
	.string "Du solltest ein Vogel-Pokémon\n"
	.string "damit ausrüsten.$"

Route40_Text_MonicaMonday::
	.string "Monja: Meine Brüder und\n"
	.string "Schwestern sind überall.\p"
	.string "Schau mal, ob du sie alle\n"
	.string "finden kannst!$"

Route40_Text_MonicaNotMonday:
	.string "MONJA: Ich\n"
	.string "fürchte, heute ist nicht Montag. Wie\l"
	.string "schade…$"

Route40_Text_MonicaNope:
	.string "Nicht dieser.$"

Rotue40_EventScript_Monica::
	lock
	faceplayer
	goto_if_set FLAG_GOT_SHARP_BEAK, Rotue40_EventScript_MonicaCompleted
	msgbox Route40_Text_Monica, MSGBOX_DEFAULT
	closemessage
	multichoice 20, 0, MULTI_DAYS_OF_WEEK, FALSE
	switch VAR_RESULT
	case 0, Rotue40_EventScript_MonicaNope
	case 1, Rotue40_EventScript_MonicaYes
	case 2, Rotue40_EventScript_MonicaNope
	case 3, Rotue40_EventScript_MonicaNope
	case 4, Rotue40_EventScript_MonicaNope
	case 5, Rotue40_EventScript_MonicaNope
	case 6, Rotue40_EventScript_MonicaNope
	case 7 Rotue40_EventScript_MonicaCancel
	case MULTI_B_PRESSED, Rotue40_EventScript_MonicaCancel
	closemessage
	release
	end
Rotue40_EventScript_MonicaYes::
	msgbox Route40_Text_MonicaGivesGift, MSGBOX_DEFAULT
	giveitem ITEM_SHARP_BEAK
	goto_if_eq VAR_RESULT, FALSE, Common_EventScript_ShowBagIsFull
	setflag FLAG_GOT_SHARP_BEAK
	msgbox Route40_Text_MonicaGaveGift, MSGBOX_DEFAULT
	closemessage
	release
	end
Rotue40_EventScript_MonicaNope::
	msgbox Route40_Text_MonicaNope, MSGBOX_DEFAULT
	closemessage
	release
	end
Rotue40_EventScript_MonicaCancel::
	closemessage
	release
	end
Rotue40_EventScript_MonicaCompleted::
	msgbox Route40_Text_MonicaMonday, MSGBOX_DEFAULT
	closemessage
	release
	end
