SeafoamIslands_Gym_hns_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, SeafoamIslands_Gym_OnTransition
	.byte 0

SeafoamIslands_Gym_OnTransition: 
	setflag FLAG_TEMP_1
	end

SeafoamIslands_Gym_EventScript_Blaine::
	lock
	faceplayer
	goto_if_set FLAG_DEFEATED_JOHTO_CINNABAR_GYM, SeafoamIslands_Gym_EventScript_Blaine_Defeated
	msgbox SeafoamIslands_Gym_Text_BlaineIntro, MSGBOX_DEFAULT
	trainerbattle_no_intro TRAINER_BLAINE, SeafoamIslands_Gym_Text_BlaineWinLoss
	message SeafoamIslands_Gym_Text_ReceivedVolcanoBadge
	waitmessage
	call Common_EventScript_PlayGymBadgeFanfare
	msgbox SeafoamIslands_Gym_Text_TM, MSGBOX_DEFAULT
	giveitem ITEM_TM_OVERHEAT
	setflag FLAG_BADGE15_GET
	setflag FLAG_DEFEATED_JOHTO_CINNABAR_GYM
	addvar VAR_NUM_BADGES, 1
	setvar VAR_0x8008, 15
	clearflag FLAG_HIDE_SEAFOAM_GYMGUY
	call Common_EventScript_SetGymTrainers
	closemessage
	release
	end

SeafoamIslands_Gym_EventScript_Blaine_Defeated::
	msgbox SeafoamIslands_Gym_Text_BlaineAfterBattle, MSGBOX_DEFAULT
	closemessage
	release
	end

SeafomIslands2_EventScript_GymGuide::
	goto_if_set FLAG_TEMP_2, SeafomIslands2_EventScript_GymGuide2
	msgbox SeafoamIslands_Gym_Text_GymGuideWin, MSGBOX_NPC
	setflag FLAG_TEMP_2
	end
SeafomIslands2_EventScript_GymGuide2::
	msgbox SeafoamIslands_Gym_Text_GymGuideWin2, MSGBOX_NPC
	end

SeafoamIslands_Gym_EventScript_GymStatue::
	lockall
	goto_if_set FLAG_BADGE15_GET, SeafoamIslands_Gym_EventScript_GymStatuePostVictory
	msgbox SeafoamIslands_Gym_Text_GymStatue
	releaseall
	end

SeafoamIslands_Gym_EventScript_GymStatuePostVictory::
	msgbox SeafoamIslands_Gym_Text_GymStatuePlayerWon
	releaseall
	end

SeafoamIslands_Gym_Text_GymStatue::
	.string "Zinnober Pokémon Arena\n"
	.string "Leiter: Pyro\p"
	.string "GEWINNER: Blau, Rot$"

SeafoamIslands_Gym_Text_GymStatuePlayerWon::
	.string "Zinnober Pokémon Arena\n"
	.string "Leiter: Pyro\p"
	.string "GEWINNER: Blau, Rot, {PLAYER}$"

SeafoamIslands_Gym_Text_TM::
	.string "Nimm dies auch noch.\n"
	.string "Diese TM enthält das\n"
	.string "gewaltige HITZEKOLLER.\p"
	.string "Ich hoffe, dein nächster\n"
	.string "Gegner hat einen extra\l"
	.string "FEUERHEILER! Waaah!$"

SeafoamIslands_Gym_Text_BlaineIntro::
	.string "Pyro: Waaah!\p"
	.string "Meine Arena in Zinnober\n"
	.string "ist niedergebrannt.\p"
	.string "Meine feueratmenden Pokémon und ich\l"
	.string "sind\n"
	.string "durch den Vulkan\p"
	.string "obdachlos geworden.\p"
	.string "Waaah!\p"
	.string "Doch jetzt bin ich wieder\n"
	.string "als ARENALEITER hier\n"
	.string "in dieser Höhle tätig.\p"
	.string "Wenn du mich besiegst,\n"
	.string "erhältst du einen ORDEN.\p"
	.string "Ha! Bring besser einen\n"
	.string "FEUERHEILER mit!$"

SeafoamIslands_Gym_Text_BlaineWinLoss::
	.string "Pyro: Großartig...\p"
	.string "Ich bin ausgebrannt.\p"
	.string "Du hast den\n"
	.string "VULKANORDEN verdient!$"

SeafoamIslands_Gym_Text_ReceivedVolcanoBadge::
	.string "{PLAYER} erhielt den\n"
	.string "VULKANORDEN.$"

SeafoamIslands_Gym_Text_BlaineAfterBattle::
	.string "Pyro: Dieses Mal habe\n"
	.string "ich verloren.\p"
	.string "Doch nächstes Mal\n"
	.string "werde ich siegen.\p"
	.string "Wenn ich meine Arena\n"
	.string "in Zinnober neu baue,\l"
	.string "kämpfen wir erneut!$"

SeafoamIslands_Gym_Text_BlaineFightDone::
	.string "Pyro: Meine FEUER-\n"
	.string "Pokémon werden noch\n"
	.string "stärker.\p"
	.string "Warte nur ab!$"

SeafoamIslands_Gym_Text_BlaineRematch::
	.string "Pyro: Whoa!\p"
	.string "Du bist jetzt der\n"
	.string "KANTO-CHAMPION!\p"
	.string "Das ist ja heiß!\p"
	.string "Deine Fähigkeiten sind\n"
	.string "erstklassig.\p"
	.string "Ich bin immer bereit\n"
	.string "für einen Kampf.\p"
	.string "Willst du eine\n"
	.string "Revanche?$"

SeafoamIslands_Gym_Text_BlaineRematchDefeat::
	.string "Pyro: Deine Fähigkeiten\n"
	.string "sind wahrlich feurig!\p"
	.string "Du hast meine Verteid-\n"
	.string "igung verbrannt.$"

SeafoamIslands_Gym_Text_GymGuideWin::
	.string "Yo!\p"
	.string "…Hä? Schon vorbei?\p"
	.string "Tut mir leid!\p"
	.string "Die Zinnober-Arena war verschwunden,\n"
	.string "also wusste ich nicht,\p"
	.string "wo ich dich finde.\p"
	.string "Aber hey, du bist auch\n"
	.string "ohne meinen Rat stark.\p"
	.string "Ich wusste, dass du\n"
	.string "gewinnst!$"

SeafoamIslands_Gym_Text_GymGuideWin2::
	.string "Eine Pokémon-Arena kann\n"
	.string "überall sein, solange der\n"
	.string "ARENALEITER da ist.\p"
	.string "Ein Gebäude braucht es\n"
	.string "nicht.$"
