VermilionCity_House1_hns_MapScripts::
	.byte 0

VermilionCity_House1_EventScript_Fisher::
	msgbox VermilionCity_House1_Text_FishingDude, MSGBOX_NPC
	end
VermilionCity_House1_EventScript_Photo::
	msgbox VermilionCity_House1_Text_Photo, MSGBOX_NPC
	end
VermilionCity_House1_Text_FishingDude:
	.string "Ich bin der ANGEL-TYP, der\n"
	.string "Älteste der ANGEL-BRÜDER.\p"
	.string "Kennst du den ANGEL-GURU am\n"
	.string "See des Zorns?\p"
	.string "Er träumt davon, das größte\n"
	.string "Karpador der Welt zu sehen.\p"
	.string "Wenn es dir nichts ausmacht,\n"
	.string "zeig ihm ein Karpador, das du\n"
	.string "fängst.\p"
	.string "Wer weiß, vielleicht fängst du\n"
	.string "sein Traum-Karpador.$"

VermilionCity_House1_Text_Photo:
	.string "Das ist ein Foto von Leuten,\n"
	.string "die angeln…\p"
	.string "Sie haben eine tolle Zeit…$"
