.set LOCALID_DIRECTOR_OFFICE, 1
.set LOCALID_GOLDENROD_ARCHER, 2
.set LOCALID_GOLDENROD_ARIANA, 3
.set LOCALID_PETREL_OFFICE, 4
.set LOCALID_DIRECTOR_STUDIO, 5

GoldenrodCity_RadioTower_5F_hns_MapScripts::
	map_script MAP_SCRIPT_ON_LOAD, GoldenrodCity_RadioTower_5F_OnLoad
	.byte 0

GoldenrodCity_RadioTower_5F_OnLoad::
	call_if_eq VAR_GOLDENROD_CITY_STATE, 6, GoldenrodCity_RadioTower_5F_MapScript_HidePetrel
	end

GoldenrodCity_RadioTower_5F_MapScript_HidePetrel::
	clearflag FLAG_HIDE_GOLDENROD_RADIOTOWER_DIRECTOR
	setflag FLAG_HIDE_GOLDENROD_RADIOTOWER_PETREL
	return


@=======[OFFICE]==============================================================================================================================

GoldenrodCity_RadioTower_5F_EventScript_Petrel::
	lock
	goto_if_ge VAR_GOLDENROD_CITY_STATE, 10, GoldenrodCity_RadioTower_5F_EventScript_Director
	goto_if_eq VAR_FACING, DIR_SOUTH, GoldenrodCity_RadioTower_5F_EventScript_PetrelNorth
	faceplayer
	msgbox GoldenrodCity_RadioTower_5F_Text_FakeDirector1, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_DIRECTOR_OFFICE, GoldenrodCity_RadioTower_5F_Movement_Spin
	waitmovement 0
	setflag FLAG_HIDE_GOLDENROD_RADIOTOWER_DIRECTOR
	removeobject LOCALID_DIRECTOR_OFFICE
	clearflag FLAG_HIDE_GOLDENROD_RADIOTOWER_PETREL
	addobject LOCALID_PETREL_OFFICE
	applymovement LOCALID_PETREL_OFFICE, GoldenrodCity_RadioTower_5F_Movement_Spin2
	waitmovement 0
	msgbox GoldenrodCity_RadioTower_5F_Text_FakeDirector2, MSGBOX_DEFAULT
	trainerbattle_no_intro TRAINER_PETREL_2, GoldenrodCity_RadioTower_5F_Text_FakeDirectorWin
	msgbox GoldenrodCity_RadioTower_5F_Text_FakeDirectorAfter, MSGBOX_DEFAULT
	giveitem ITEM_BASEMENT_KEY
	setvar VAR_GOLDENROD_CITY_STATE, 7
	clearflag FLAG_HIDE_GOLDENROD_UNDERGROUND_KIMONO
	closemessage
	release
	end

GoldenrodCity_RadioTower_5F_EventScript_PetrelNorth::
	end

GoldenrodCity_RadioTower_5F_EventScript_Petrel2::
	lock
	faceplayer
	msgbox GoldenrodCity_RadioTower_5F_Text_FakeDirectorAfter2, MSGBOX_DEFAULT
	closemessage
	release
	end

GoldenrodCity_RadioTower_5F_EventScript_Director::
	lock
	faceplayer
	msgbox GoldenrodCity_RadioTower_5F_Text_DirectorIntro, MSGBOX_DEFAULT
	closemessage
	release
	end

GoldenrodCity_RadioTower_5F_Movement_Spin:
	face_right
	delay_8
	face_up
	delay_8
	face_left
	delay_8
	face_down
	delay_8
	face_right
	delay_4
	face_up
	delay_4
	face_left
	delay_4
	face_down
	delay_4
	face_right
	delay_2
	face_up
	delay_2
	face_left
	delay_2
	face_down
	step_end


GoldenrodCity_RadioTower_5F_Movement_Spin2:
	face_right
	delay_2
	face_up
	delay_2
	face_left
	delay_2
	face_down
	step_end


GoldenrodCity_RadioTower_5F_Text_FakeDirector1:
	.string "D-du! Du willst mich retten?$"

GoldenrodCity_RadioTower_5F_Text_FakeDirector2:
	.string "Hast du das etwa erwartet?\p"
	.string "Falsch! Ich bin ein Betrüger!\p"
	.string "Willst du wissen, wo wir den\n"
	.string "ECHTEN DIREKTOR versteckt\n"
	.string "haben?\p"
	.string "Schon gut, ich sag es dir. Aber\n"
	.string "nur, wenn du mich besiegst!$"

GoldenrodCity_RadioTower_5F_Text_FakeDirectorWin:
	.string "Schon gut! Ich sag dir, wo er ist.$"

GoldenrodCity_RadioTower_5F_Text_FakeDirectorAfter:
	.string "Der Boss hat den DIREKTOR im\n"
	.string "UNTERGRUND-LAGER versteckt.\p"
	.string "Es liegt ganz am Ende des\n"
	.string "UNTERGRUND.\p"
	.string "Ich bin nett und gebe dir den\n"
	.string "Kelleröffner für das\n"
	.string "UNTERGRUND-LAGER.\p"
	.string "Aber ich bezweifle, dass du\n"
	.string "so weit kommst.$"

GoldenrodCity_RadioTower_5F_Text_FakeDirectorAfter2:
	.string "Der Boss hat den DIREKTOR im\n"
	.string "UNTERGRUND-LAGER versteckt.\p"
	.string "Es liegt ganz am Ende des\n"
	.string "UNTERGRUND.\p"
	.string "Mit dem Kelleröffner kommst du\n"
	.string "ins UNTERGRUND-LAGER.\p"
	.string "Aber ich bezweifle, dass du\n"
	.string "so weit kommst.$"

@=======[STUDIO]==============================================================================================================================

GoldenrodCity_RadioTower_5F_EventScript_Ben::
	lock
	faceplayer
	msgbox GoldenrodCity_RadioTower_5F_Text_Ben, MSGBOX_DEFAULT
	closemessage
	release
	end

GoldenrodRaidoTower4_EventScript_ARIANA::
	trainerbattle_single TRAINER_ARIANA_2 GoldenrodCity_RadioTower_5F_Text_ExecutiveF1Seen, GoldenrodCity_RadioTower_5F_Text_ExecutiveF1Beaten
	msgbox GoldenrodCity_RadioTower_5F_Text_ExecutiveF1After, MSGBOX_AUTOCLOSE
	end

GoldenrodCity_RadioTower_5F_EventScript_Archer::
	lock
	faceplayer
	msgbox GoldenrodCity_RadioTower_5F_Text_RocketBossSeen, MSGBOX_DEFAULT
	trainerbattle_no_intro TRAINER_ARCHER, GoldenrodCity_RadioTower_5F_Text_RocketBossBeaten
	msgbox GoldenrodCity_RadioTower_5F_Text_RocketBossAfter, MSGBOX_DEFAULT
	delay 55
	closemessage
	fadescreen FADE_TO_BLACK
	setflag FLAG_HIDE_GOLDENROD_ROCKETS
	playse SE_EXIT
	setvar VAR_GOLDENROD_CITY_STATE, 10
	removeobject LOCALID_GOLDENROD_ARCHER
	removeobject LOCALID_GOLDENROD_ARIANA
	setflag FLAG_HIDE_GOLDENROD_RADIOTOWER_PETREL
	clearflag FLAG_HIDE_GOLDENROD_RADIOTOWER_DIRECTOR
	removeobject LOCALID_PETREL_OFFICE
	addobject LOCALID_DIRECTOR_STUDIO
	playbgm MUS_HG_GOLDENROD, TRUE
	delay 120
	fadescreen FADE_FROM_BLACK
	goto_if_eq VAR_FACING, DIR_SOUTH, GoldenrodCity_RadioTower_5F_EventScript_WingTop
	goto_if_eq VAR_FACING, DIR_WEST, GoldenrodCity_RadioTower_5F_EventScript_WingMid
	goto_if_eq VAR_FACING, DIR_NORTH, GoldenrodCity_RadioTower_5F_EventScript_WingBot
	release
	end

GoldenrodCity_RadioTower_5F_EventScript_WingTop::
	applymovement LOCALID_DIRECTOR_STUDIO, GoldenrodCity_RadioTower_5F_Movement_WalkToPlayerTop
	waitmovement 0
	turnobject LOCALID_PLAYER, DIR_EAST
	msgbox GoldenrodCity_RadioTower_5F_Text_DirectorThanks, MSGBOX_DEFAULT
	closemessage
	call_if_eq VAR_LUGIA_OR_HOOH, 1,  GoldenrodCity_RadioTower_5F_EventScript_GiveTidalWing
	call_if_eq VAR_LUGIA_OR_HOOH, 2, GoldenrodCity_RadioTower_5F_EventScript_GiveClearWing
	applymovement LOCALID_DIRECTOR_STUDIO, GoldenrodCity_RadioTower_5F_Movement_LeaveTop
	waitmovement 0
	goto GoldenrodCity_RadioTower_5F_Fakeout
	end

GoldenrodCity_RadioTower_5F_EventScript_WingMid::
	applymovement LOCALID_DIRECTOR_STUDIO, GoldenrodCity_RadioTower_5F_Movement_WalkToPlayerMid
	waitmovement 0
	turnobject LOCALID_PLAYER, DIR_EAST
	msgbox GoldenrodCity_RadioTower_5F_Text_DirectorThanks, MSGBOX_DEFAULT
	closemessage
	call_if_eq VAR_LUGIA_OR_HOOH, 1,  GoldenrodCity_RadioTower_5F_EventScript_GiveTidalWing
	call_if_eq VAR_LUGIA_OR_HOOH, 2, GoldenrodCity_RadioTower_5F_EventScript_GiveClearWing
	applymovement LOCALID_DIRECTOR_STUDIO, GoldenrodCity_RadioTower_5F_Movement_LeaveMid
	waitmovement 0
	goto GoldenrodCity_RadioTower_5F_Fakeout
	end

GoldenrodCity_RadioTower_5F_EventScript_WingBot::
	applymovement LOCALID_DIRECTOR_STUDIO, GoldenrodCity_RadioTower_5F_Movement_WalkToPlayerBot
	waitmovement 0
	turnobject LOCALID_PLAYER, DIR_EAST
	msgbox GoldenrodCity_RadioTower_5F_Text_DirectorThanks, MSGBOX_DEFAULT
	closemessage
	call_if_eq VAR_LUGIA_OR_HOOH, 1,  GoldenrodCity_RadioTower_5F_EventScript_GiveTidalWing
	call_if_eq VAR_LUGIA_OR_HOOH, 2, GoldenrodCity_RadioTower_5F_EventScript_GiveClearWing
	applymovement LOCALID_DIRECTOR_STUDIO, GoldenrodCity_RadioTower_5F_Movement_LeaveBot
	waitmovement 0
	goto GoldenrodCity_RadioTower_5F_Fakeout
	end

GoldenrodCity_RadioTower_5F_EventScript_GiveTidalWing::
	giveitem ITEM_SILVER_WING
	msgbox GoldenrodCity_RadioTower_5F_Text_DirectorTidalWingExplanation, MSGBOX_DEFAULT
	closemessage
	release
	return

GoldenrodCity_RadioTower_5F_EventScript_GiveClearWing::
	giveitem ITEM_RAINBOW_WING
	msgbox GoldenrodCity_RadioTower_5F_Text_DirectorClearWingExplanation, MSGBOX_DEFAULT
	closemessage
	release
	return

GoldenrodCity_RadioTower_5F_Fakeout::
	playse SE_PIN
	applymovement LOCALID_DIRECTOR_STUDIO, Common_Movement_ExclamationMark
	delay 60
	turnobject LOCALID_DIRECTOR_STUDIO, DIR_WEST
	msgbox GoldenrodCity_RadioTower_5F_Text_DirectorLegendary, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_DIRECTOR_STUDIO, GoldenrodCity_RadioTower_5F_Movement_Leave1
	waitmovement 0
	playse SE_PIN
	applymovement LOCALID_DIRECTOR_STUDIO, Common_Movement_ExclamationMark
	delay 60
	turnobject LOCALID_DIRECTOR_STUDIO, DIR_SOUTH
	msgbox GoldenrodCity_RadioTower_5F_Text_DirectorFakeout, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_DIRECTOR_STUDIO, GoldenrodCity_RadioTower_5F_Movement_Leave2
	waitmovement 0
	setflag FLAG_HIDE_GOLDENROD_RADIOTOWER_DIRECTOR_2
	removeobject LOCALID_DIRECTOR_STUDIO
	setvar VAR_MAHOGANY_TOWN_STATE, 17
	release
	end

GoldenrodCity_RadioTower_5F_EventScript_Trigger_NPCS::
	clearflag FLAG_HIDE_GOLDENROD_NPCS
	setvar VAR_GOLDENROD_CITY_STATE, 11
	end

GoldenrodCity_RadioTower_5F_Movement_WalkToPlayerTop:
	walk_down
	walk_down
	walk_down
	walk_down
	walk_down
	walk_down
	walk_left
	walk_left
	walk_left
	step_end

GoldenrodCity_RadioTower_5F_Movement_LeaveTop:
	walk_right
	walk_right
	walk_right
	step_end

GoldenrodCity_RadioTower_5F_Movement_WalkToPlayerMid:
	walk_down
	walk_down
	walk_down
	walk_down
	walk_down
	walk_down
	walk_down
	walk_left
	walk_left
	step_end


GoldenrodCity_RadioTower_5F_Movement_LeaveMid:
	walk_right
	walk_right
	step_end

GoldenrodCity_RadioTower_5F_Movement_WalkToPlayerBot:
	walk_down
	walk_down
	walk_down
	walk_down
	walk_down
	walk_down
	walk_down
	walk_down
	walk_left
	walk_left
	walk_left
	step_end

GoldenrodCity_RadioTower_5F_Movement_LeaveBot:
	walk_right
	walk_right
	walk_right
	step_end

GoldenrodCity_RadioTower_5F_Movement_Leave1:
	walk_up
	walk_up
	step_end

GoldenrodCity_RadioTower_5F_Movement_Leave2:
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

GoldenrodCity_RadioTower_5F_Text_ExecutiveF1Seen:
	.string "Erinnerst du dich an mich aus dem\n"
	.string "VERSTECK in Mahagonia?\p"
	.string "Mein Boss hat mich ausgeschimpft,\n"
	.string "aber ich bin stärker!\p"
	.string "Damals verlor ich...\n"
	.string "Doch heute nicht!$"

GoldenrodCity_RadioTower_5F_Text_ExecutiveF1Beaten:
	.string "Das... das darf nicht sein!\p"
	.string "Ich gab alles und verlor doch…\p"
	.string "Es tut mir leid, Giovanni…$"

GoldenrodCity_RadioTower_5F_Text_ExecutiveF1After:
	.string "{PLAYER}, richtig?\p"
	.string "Ein Gör wie du versteht die Größe\n"
	.string "von TEAM ROCKET nicht.\p"
	.string "Schade… Ich bewundere deine Stärke.$"

GoldenrodCity_RadioTower_5F_Text_RocketBossSeen:
	.string "Oh? Du hast es bis hierher\n"
	.string "geschafft?\p"
	.string "Du bist ein starker Trainer.\p"
	.string "Wir übernehmen die\n"
	.string "RADIOSTATION und kündigen unser\n"
	.string "Comeback an.\p"
	.string "So wird unser Boss Giovanni aus\n"
	.string "seinem Training zurückkehren!\p"
	.string "Wir werden zu alter Größe\n"
	.string "zurückfinden…\p"
	.string "Ich lasse dich unsere Pläne nicht\n"
	.string "durchkreuzen!$"

GoldenrodCity_RadioTower_5F_Text_RocketBossBeaten:
	.string "Nein! Verzeih mir, Giovanni!$"

GoldenrodCity_RadioTower_5F_Text_RocketBossAfter:
	.string "Wie konnte das geschehen?\p"
	.string "All unsere Träume... dahin.\p"
	.string "Ich war dieser Aufgabe doch\n"
	.string "nicht gewachsen.\p"
	.string "Wie Giovanni einst werde ich TEAM\n"
	.string "ROCKET heute auflösen.\p"
	.string "Leb wohl.$"

GoldenrodCity_RadioTower_5F_Text_DirectorThanks:
	.string "INTENDANT: {PLAYER}, danke!\p"
	.string "Dein Mut hat Pokémon im ganzen\n"
	.string "Land gerettet.\p"
	.string "Es ist nicht viel, aber bitte,\n"
	.string "nimm dies.$"

GoldenrodCity_RadioTower_5F_Text_DirectorClearWingExplanation:
	.string "Hier stand einst ein alter Turm in\n"
	.string "Dukatia City.\p"
	.string "Er war morsch und klapprig…\p"
	.string "Darum ersetzten wir ihn durch den\n"
	.string "RADIOTURM.\p"
	.string "Beim Bau fanden wir diese Feder.\p"
	.string "Man sagt, früher lebten viele\n"
	.string "Pokémon in DUKATIA.\p"
	.string "Vielleicht…\p"
	.string "Hat sie etwas mit dem ZINNTURM\n"
	.string "in Teak City zu tun…\p"
	.string "Ich gehe nun in mein Büro.$"

GoldenrodCity_RadioTower_5F_Text_DirectorTidalWingExplanation:
	.string "Hier stand einst ein alter Turm in\n"
	.string "Dukatia City.\p"
	.string "Er war alt und klapprig…\p"
	.string "Darum bauten wir den RADIOTURM.\p"
	.string "Dabei fanden wir diese Feder.\p"
	.string "Früher lebten viele Pokémon in\n"
	.string "DUKATIA.\p"
	.string "Vielleicht…\p"
	.string "Hat sie etwas mit den\n"
	.string "Strudelinseln bei Anemonia zu tun…\p"
	.string "Ich gehe nun in mein Büro.$"

GoldenrodCity_RadioTower_5F_Text_DirectorLegendary:
	.string "Ah!\p"
	.string "Da fällt mir ein…\p"
	.string "Die Feder, die ich dir gab…\n"
	.string "Sie soll mit den LEGENDÄREN\n"
	.string "Pokémon zu tun haben.\p"
	.string "Aber! Allein die Feder reicht nicht…\p"
	.string "Man braucht noch etwas\n"
	.string "anderes… oder so.\p"
	.string "Was war das nur…?\p"
	.string "Ich erinnere mich nicht.$"

GoldenrodCity_RadioTower_5F_Text_DirectorFakeout:
	.string "Erwartest du etwas?\n"
	.string "Das nennt man Mogelhieb!\p"
	.string "Jetzt aber wirklich:\n"
	.string "Ich muss ins Büro. Tschüss!$"

GoldenrodCity_RadioTower_5F_Text_DirectorIntro:
	.string "INTENDANT: Hallo, {PLAYER}!\p"
	.string "Weißt du… Ich liebe Pokémon.\p"
	.string "Ich baute diesen Radioturm, um\n"
	.string "meine Liebe dafür zu zeigen.\p"
	.string "Ich hoffe, die Leute mögen\n"
	.string "unsere Programme.$"

GoldenrodCity_RadioTower_5F_Text_Ben:
	.string "Ben: Hörst du unsere Musik?$"

GoldenrodCity_RadioTower_5F_Text_DirectorOfficeSign:
	.string "4S   BÜRO DES INTENDANTEN$"

GoldenrodCity_RadioTower_5F_Text_Studio1Sign:
	.string "4S   STUDIO 1$"

