.set LOCALID_ROUTE42_EUSINE, 19
.set LOCALID_ROUTE42_SUICUNE, 17

Route42_hns_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, Route42_MapScript_OnTransition
	map_script MAP_SCRIPT_ON_RESUME, SetTimeEncounters
	.byte 0

Route42_MapScript_OnTransition::
	call_if_set FLAG_HIDE_ROUTE42_SUICUNE, Route42_MapScript_HideTrigger
	callnative SetTimeBasedEncounters
	end

Route42_MapScript_HideTrigger::
	setvar VAR_TEMP_0, 1
	return

Route42_EventScript_Suicune_Trigger::
	lock
	playmoncry SPECIES_SUICUNE, CRY_MODE_NORMAL
	applymovement LOCALID_ROUTE42_SUICUNE, Route42_Movement_Suicune1
	playse SE_LEDGE
	waitse
	playse SE_LEDGE
	waitse
	waitmovement 0
	waitmoncry
	playse SE_PIN
	applymovement LOCALID_PLAYER, Common_Movement_ExclamationMark
	delay 60
	applymovement LOCALID_ROUTE42_SUICUNE, Route42_Movement_Suicune2
	playse SE_LEDGE
	delay 30
	playse SE_LEDGE
	delay 30
	playse SE_LEDGE
	delay 30
	playse SE_LEDGE
	delay 30
	waitmovement 0

	playmoncry SPECIES_SUICUNE, CRY_MODE_NORMAL
	applymovement LOCALID_ROUTE42_SUICUNE, Route42_Movement_Suicune3
	applymovement LOCALID_PLAYER, Route42_Movement_Player
	playse SE_LEDGE
	delay 60
	playse SE_LEDGE
	delay 30
	playse SE_LEDGE
	delay 30
	playse SE_LEDGE
	delay 30
	playse SE_LEDGE
	delay 30
	playse SE_LEDGE
	waitmovement LOCALID_ROUTE42_SUICUNE
	waitmovement 0
	delay 60
	removeobject LOCALID_ROUTE42_SUICUNE
	setflag FLAG_HIDE_ROUTE42_SUICUNE
	clearflag FLAG_HIDE_ROUTE42_EUSINE
	addobject LOCALID_ROUTE42_EUSINE
	playse SE_EXIT
	turnobject LOCALID_PLAYER, DIR_EAST
	applymovement LOCALID_ROUTE42_EUSINE, Route42_Movement_Eusine1
	waitmovement 0
	msgbox Route42_Text_EusineAdmireSuicune, MSGBOX_DEFAULT
	closemessage
	turnobject LOCALID_ROUTE42_EUSINE, DIR_WEST
	msgbox Route42_Text_EusineJealous, MSGBOX_DEFAULT
	turnobject LOCALID_ROUTE42_EUSINE, DIR_EAST
	msgbox Route42_Text_EusineWontGiveUp, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_ROUTE42_EUSINE, Route42_Movement_Eusine2
	waitmovement 0
	setflag FLAG_HIDE_ROUTE42_EUSINE
	removeobject LOCALID_ROUTE42_EUSINE
	setvar VAR_TEMP_0, 1
	call_if_eq VAR_SUICUNE_ENCOUNTERS, 2, Route42_EventScript_DoneJohtoSuicune
	release
	end

Route42_EventScript_DoneJohtoSuicune::
	setvar VAR_SUICUNE_ENCOUNTERS, 3
	return

Route42_Movement_Suicune1:
	jump_in_place_right_left
	jump_in_place_right_left
	step_end

Route42_Movement_Suicune2:
	jump_2_left
	jump_2_left
	jump_2_left
	jump_2_up
	step_end

Route42_Movement_Suicune3:
	jump_in_place_up
	delay_2
	face_up
	jump_2_up
	jump_2_right
	jump_2_right
	jump_2_right
	jump_2_right
	jump_2_right
	step_end

Route42_Movement_Player:
	lock_facing_direction
	delay_2
	jump_2_up
	unlock_facing_direction
	step_end

Route42_Movement_Eusine1:
	walk_down
	walk_down
	walk_left
	face_right
	step_end

Route42_Movement_Eusine2:
	walk_fast_right
	walk_fast_right
	walk_fast_right
	walk_fast_right
	walk_fast_right
	walk_fast_right
	walk_fast_right
	walk_fast_right
	walk_fast_right
	step_end

Route42_Text_EusineAdmireSuicune::
	.string "Eusin: Suicune...\n"
	.string "Wie mutig es ist!\p"
	.string "Wie erfrischend es ist!\n"
	.string "Wie schön es ist!\p"
	.string "Und wie schnell es sich bewegt!$"

Route42_Text_EusineJealous::
	.string "{PLAYER}!\p"
	.string "Du scheinst da zu sein, wo\n"
	.string "Suicune erscheinen könnte.\p"
	.string "Nun, das ist in Ordnung.\l"
	.string "Mein Drang, Suicune zu suchen,\n"
	.string "geht weit über deinen hinaus...\p"
	.string "Mein Großvater war sehr\n"
	.string "von Mythen begeistert.\p"
	.string "Von ihm habe ich so viele\n"
	.string "Geschichten über Suicune gehört.$"

Route42_Text_EusineWontGiveUp::
	.string "Suicune... Ich werde dich weiter\l"
	.string "verfolgen\n"
	.string "bis ich herausgefunden habe,\p"
	.string "was du suchst...\p"
	.string "Hörst du mich!$"


Route42_EventScript_Tully::
	trainerbattle_single TRAINER_TULLY Route42_Text_FisherTullySeen, Route42_Text_FisherTullyBeaten
	msgbox Route42_Text_FisherTullyAfter, MSGBOX_AUTOCLOSE
	end

Route42_EventScript_Ben::
	trainerbattle_single TRAINER_BENJAMIN Route42_Text_HikerBenjaminSeen, Route42_Text_HikerBenjaminBeaten
	msgbox Route42_Text_HikerBenjaminAfter, MSGBOX_AUTOCLOSE
	end

Route42_EventScript_Shane::
	trainerbattle_single TRAINER_SHANE Route42_Text_PokemaniacShaneSeen, Route42_Text_PokemaniacShaneBeaten
	msgbox Route42_Text_PokemaniacShaneAfter, MSGBOX_AUTOCLOSE
	end

Route42_EventScript_Sign::
	lock
	msgbox Route42_Text_Sign1, MSGBOX_SIGN
	closemessage
	release
	end

Route42_EventScript_MortarSign::
	lock
	msgbox Route42_Text_MtMortarSign1, MSGBOX_SIGN
	closemessage
	release
	end

Route42_EventScript_Item_SuperPotion::
	finditem ITEM_SUPER_POTION
	end
Route42_EventScript_Item_Mint::
	finditem ITEM_MODEST_MINT
	end
Route42_EventScript_Item_UltraBall::
	finditem ITEM_ULTRA_BALL
	end

Route42_Text_FisherTullySeen:
	.string "Jetzt demonstriere\n"
	.string "ich dir die Kraft des Pokémon, das ich\l"
	.string "gefangen habe!$"

Route42_Text_FisherTullyBeaten:
	.string "Was? Das kann nicht sein.$"

Route42_Text_FisherTullyAfter::
	.string "Ich will der Champ werden,\n"
	.string "mit den Pokémon, die ich selbst\n"
	.string "gefangen habe.\p"
	.string "Das ist das Beste am Angeln!$"

Route42_Text_HikerBenjaminSeen:
	.string "Ach, ist das\n"
	.string "schön, im Freien zu sein! Ich fühle\l"
	.string "mich so frei!$"

Route42_Text_HikerBenjaminBeaten:
	.string "Hahaha!$"

Route42_Text_HikerBenjaminAfter::
	.string "Verlieren fühlt sich unbedeutend an,\n"
	.string "wenn man in den großen Himmel schaut!$"

Route42_Text_PokemaniacShaneSeen:
	.string "HEH!\p"
	.string "Das ist mein\n"
	.string "Geheimversteck! Verschwinde, du\l"
	.string "Außenseiter!$"

Route42_Text_PokemaniacShaneBeaten:
	.string "Ich hätte meinen\n"
	.string "MONDSTEIN benutzen sollen…$"

Route42_Text_PokemaniacShaneAfter::
	.string "Du arbeitest an einem POKéDEX?\p"
	.string "Wow, du musst einige richtig\n"
	.string "seltene Pokémon kennen!\p"
	.string "Darf ich es mir mal ansehen?\n"
	.string "Bitte?$"

Route42_Text_Sign1:
	.string "ROUTE 42\p"
	.string "TEAK CITY - MAHAGONIA CITY$"

Route42_Text_MtMortarSign1:
	.string "KESSELBERG\p"
	.string "WASSERFALLHÖHLE drinnen$"
