LakeOfRage_House1_hns_MapScripts::
	.byte 0

LakeOfRage_House1_EventScript_HiddenPowerGuy::
	lock
	faceplayer
	goto_if_set FLAG_GOT_HIDDEN_POWER, LakeOfRage_House1_EventScript_HiddenPowerGuyAfter
	msgbox HiddenPowerGuy_Text_Intro, MSGBOX_DEFAULT
	giveitem ITEM_TM_HIDDEN_POWER
	msgbox HiddenPowerGuy_Text_Explanation, MSGBOX_DEFAULT
	setflag FLAG_GOT_HIDDEN_POWER
	closemessage
	release
	end

LakeOfRage_House1_EventScript_HiddenPowerGuyAfter::
	msgbox HiddenPowerGuy_Text_Meditating, MSGBOX_DEFAULT
	closemessage
	release
	end

HiddenPowerGuy_Text_Intro:
	.string "…Du bist viel herumgekommen…\p"
	.string "Ich habe hier meditiert. In mir\p"
	.string "ist eine neue Kraft zum Leben erwacht.\n"
	.string "\p"
	.string "Lass mich meine Kraft mit deinen\p"
	.string "Pokémon teilen. Nimm dies, Kind.$"

HiddenPowerGuy_Text_Explanation:
	.string "Siehst du das? Es ist Kraftreserve!\p"
	.string "Sie entfesselt die Kraft von Pokémon\n"
	.string "für Angriffe.\p"
	.string "Merke dir: Typ und Stärke hängen\n"
	.string "vom Pokémon ab, das sie einsetzt.$"

HiddenPowerGuy_Text_Meditating:
	.string "Ich meditiere…$"
