.set LOCALID_ROUTE27_FATMAN, 1

Route27_hns_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, Route27_OnTransition
	map_script MAP_SCRIPT_ON_RESUME, SetTimeEncounters
	.byte 0

Route27_OnTransition: 
	callnative SetTimeBasedEncounters
	end

Route27_EventScript_BaobaCall::
	pokenavcall BlackthornCity_Text_BaobaCall
	waitmessage
	delay 30
	setflag FLAG_SAFARI_ZONE_WEST_EXPANSION
    setvar VAR_ROUTE27_BAOBA_CALL, 1
	end

Route27_EventScript_FirstSteps::
    lock
    playse SE_PIN
    setflag FLAG_VISITED_KANTO
    applymovement2 LOCALID_ROUTE27_FATMAN, Common_Movement_ExclamationMark
    turnobject LOCALID_ROUTE27_FATMAN, DIR_WEST
    delay 30
    getplayerxy VAR_TEMP_0, VAR_TEMP_1
    call_if_eq VAR_TEMP_1, 24, Route27_EventScript_FirstStepsWalkTop
    call_if_eq VAR_TEMP_1, 25, Route27_EventScript_FirstStepsWalkBot

    msgbox Route27_Text_FisherHey, MSGBOX_DEFAULT
    msgbox Route27_Text_FisherMessage, MSGBOX_DEFAULT
    closemessage
    turnobject LOCALID_ROUTE27_FATMAN, DIR_SOUTH

    @integrated flagheap
    setflag FLAG_HIDE_VICTORY_ROAD_SILVER
    setflag FLAG_HIDE_INDIGO_PLATEAU_SILVER
    setflag FLAG_HIDE_INDIGO_PLATEAU_MARY_OAK
    
    clearflag FLAG_GOT_TM_SANDSTORM
    clearflag FLAG_INDIGOJUNCTION_HIDE_SILVER_GUARD
    clearflag FLAG_INDIGOJUNCTION_HIDE_KANTO_GUARD

    setvar VAR_ROUTE27_STATE, 1
    release
    end

Route27_EventScript_FirstStepsWalkTop::
    applymovement2 LOCALID_ROUTE27_FATMAN, Route27_Movement_WalkTop
    waitmovement 0
    return
Route27_EventScript_FirstStepsWalkBot::
    applymovement2 LOCALID_ROUTE27_FATMAN, Route27_Movement_WalkBot
    waitmovement 0
    return

Route27_Movement_WalkTop:
    face_left
    walk_left
    step_end

Route27_Movement_WalkBot:
    walk_down
    walk_left
    step_end

Route27_EventScript_Item_Moonstone::
    finditem ITEM_MOON_STONE
    end

Route27_EventScript_Item_RareCandy::
    finditem ITEM_RARE_CANDY
    end

Route27_EventScript_Item_SolarBeam::
    finditem ITEM_TM_SOLAR_BEAM
    end

Route27_EventScript_Item_Revive::
    finditem ITEM_REVIVE
    end

Route27_EventScript_Fatman::
    msgbox Route27_Text_FisherMessage, MSGBOX_NPC
    end

Route27_EventScript_Blake::
	trainerbattle_single TRAINER_BLAKE Route27_Text_CooltrainermBlakeSeen, Route27_Text_CooltrainermBlakeBeaten
	msgbox Route27_Text_CooltrainermBlakeAfter, MSGBOX_AUTOCLOSE
	end

Route27_EventScript_Brian::
	trainerbattle_single TRAINER_BRIAN Route27_Text_CooltrainermBrianSeen, Route27_Text_CooltrainermBrianBeaten
	msgbox Route27_Text_CooltrainermBrianAfter, MSGBOX_AUTOCLOSE
	end

Route27_EventScript_Reena::
	trainerbattle_single TRAINER_REENA Route27_Text_CooltrainerfReenaSeen, Route27_Text_CooltrainerfReenaBeaten
	msgbox Route27_Text_CooltrainerfReenaAfter, MSGBOX_AUTOCLOSE
	end

Route27_EventScript_Megan::
	trainerbattle_single TRAINER_MEGAN Route27_Text_CooltrainerfMeganSeen, Route27_Text_CooltrainerfMeganBeaten
	msgbox Route27_Text_CooltrainerfMeganAfter, MSGBOX_AUTOCLOSE
	end

Route27_EventScript_Gilbert::
	trainerbattle_single TRAINER_GILBERT Route27_Text_PsychicGilbertSeen, Route27_Text_PsychicGilbertBeaten
	msgbox Route27_Text_PsychicGilbertAfter, MSGBOX_AUTOCLOSE
	end

Route27_EventScript_Jose::
	trainerbattle_single TRAINER_JOSE Route27_Text_BirdKeeperJoseSeen, Route27_Text_BirdKeeperJoseBeaten
	msgbox Route27_Text_BirdKeeperJoseAfter, MSGBOX_AUTOCLOSE
	end

Route27_EventScript_Scott::
	trainerbattle_single TRAINER_SCOTT Route27_Text_FisherScottSeen, Route27_Text_FisherScottBeaten
	msgbox Route27_Text_FisherScottAfter, MSGBOX_AUTOCLOSE
	end

Route27_EventScript_TohjoFallsSign::
    msgbox TohjoFalls_Text_Sign, MSGBOX_SIGN
    end

Route27_Text_FisherHey:
	.string "Heh!$"

Route27_Text_FisherMessage:
	.string "Weißt du, was du gerade getan\n"
	.string "hast?\p"
	.string "Du hast deinen ersten Schritt\n"
	.string "nach KANTO gemacht.\p"
	.string "Sieh auf der POKéCOM-KARTE\n"
	.string "nach.$"

Route27_Text_CooltrainermBlakeSeen:
	.string "Du siehst sehr\n"
	.string "stark aus. Ich will gegen dich\l"
	.string "kämpfen!$"

Route27_Text_CooltrainermBlakeBeaten:
	.string "Juhu!$"

Route27_Text_CooltrainermBlakeAfter:
	.string "Wenn du diesen harten Weg\n"
	.string "bestehst,\p"
	.string "wird dir die Wahrheit offenbart!\p"
	.string "Hey, sorry, ich wollte nur\n"
	.string "etwas Cooles sagen.$"

Route27_Text_CooltrainermBrianSeen:
	.string "Hm? Du bist gut, nicht wahr?$"

Route27_Text_CooltrainermBrianBeaten:
	.string "Wie ich dachte!$"

Route27_Text_CooltrainermBrianAfter:
	.string "Ein guter Trainer erkennt\n"
	.string "andere gute Trainer.$"

Route27_Text_CooltrainerfReenaSeen:
	.string "Du solltest die wilden Pokémon,\p"
	.string "die hier leben, nicht unterschätzen.$"

Route27_Text_CooltrainerfReenaBeaten:
	.string "Oh! Du bist viel zu stark!$"

Route27_Text_CooltrainerfReenaAfter:
	.string "Du bist nur ein Kind, aber\n"
	.string "ich unterschätze dich nicht.$"

Route27_Text_CooltrainerfMeganSeen:
	.string "Hier kommen nur\n"
	.string "selten Menschen vorbei.\p"
	.string "Trainierst du vollkommen allein?$"

Route27_Text_CooltrainerfMeganBeaten:
	.string "Oh! Du bist wirklich stark!$"

Route27_Text_CooltrainerfMeganAfter:
	.string "Ich untersuche Pokémon vor\n"
	.string "und nach ihrer Entwicklung.\p"
	.string "Entwicklung macht Pokémon\n"
	.string "wirklich stärker.\p"
	.string "Doch entwickelte Formen\n"
	.string "lernen Attacken oft später.$"

Route27_Text_PsychicGilbertSeen:
	.string "Sag nichts!\p"
	.string "Lass mich raten, woran du denkst.\p"
	.string "Mmmmmmm…\p"
	.string "Ich weiß! Du\n"
	.string "denkst darüber nach, zur Pokémon LIGA\l"
	.string "zu gehen!$"

Route27_Text_PsychicGilbertBeaten:
	.string "Das ist zuviel!$"

Route27_Text_PsychicGilbertAfter:
	.string "Mit deinen Fähigkeiten wirst\n"
	.string "du in der LIGA bestehen.\p"
	.string "Das sagt meine Vorahnung.$"

Route27_Text_BirdKeeperJoseSeen:
	.string "Zwitscher! Zwitscher!$"

Route27_Text_BirdKeeperJoseBeaten:
	.string "Zwitscher!$"

Route27_Text_BirdKeeperJoseAfter:
	.string "BIRD KEEPERS like me Mimikry bird\n"
	.string "whistles to command Pokémon.$"

TohjoFalls_Text_Sign:
	.string "TOHJO-FÄLLE\p"
	.string "Die Verbindung\n"
	.string "zwischen KANTO und JOHTO$"

Route27_Text_FisherScottSeen:
	.string "Heute fühle ich mich grossartig!\p"
	.string "Ich fühle mich so\n"
	.string "stark, dass ich den LIGA-CHAMP\l"
	.string "besiegen könnte!$"

Route27_Text_FisherScottBeaten:
	.string "Nein! Nicht in diesem Kampf!$"

Route27_Text_FisherScottAfter:
	.string "Genau wie beim Angeln,\n"
	.string "wenn du bei Pokémon aufgibst,\l"
	.string "ist alles vorbei.$"
