ViridianCity_Mart_hns_MapScripts::
	.byte 0

ViridianCity_Mart_EventScript_Lass::
	msgbox ViridianMart_Text_Lass, MSGBOX_NPC
	end

ViridianCity_Mart_EventScript_Cooltrainer::
	msgbox ViridianMart_Text_CooltrainerM, MSGBOX_NPC
	end

ViridianMart_Text_Lass:
	.string "Der ARENALEITER hier ist total cool.$"

ViridianMart_Text_CooltrainerM:
	.string "Warst du schon auf\n"
	.string "der ZINNOBERINSEL?\p"
	.string "Es ist gleich die\n"
	.string "nächste Insel südlich von hier.$"

