.set LOCALID_OLIVINE_CITY_GYM_NPC1, 3
.set LOCALID_OLIVINE_CITY_GYM_NPC2, 2

OlivineCity_Gym_hns_MapScripts::
	.byte 0

OlivineCity_Gym_EventScript_Gent::
	lock
	faceplayer
	goto_if_set FLAG_DEFEATED_OLIVINE_CITY_GYM, OlivineCity_Gym_EventScript_Gent2
	msgbox OlivineCity_Gym_Text_Gent, MSGBOX_DEFAULT
	closemessage
	release
	end

OlivineCity_Gym_EventScript_Gent2::
	msgbox OlivineCity_Gym_Text_Gent2, MSGBOX_DEFAULT
	closemessage
	release
	end

OlivineCity_Gym_TriggerRow1::
	lock
	setvar VAR_TEMP_0, LOCALID_OLIVINE_CITY_GYM_NPC1
	playse SE_PIN
	applymovement VAR_TEMP_0, Common_Movement_ExclamationMark
	delay 60
	getplayerxy VAR_TEMP_1, VAR_TEMP_2
	call_if_eq VAR_TEMP_1, 6, OlivineCity_Gym_EventScript_MoveLeft4
	call_if_eq VAR_TEMP_1, 7, OlivineCity_Gym_EventScript_MoveLeft3
	call_if_eq VAR_TEMP_1, 8, OlivineCity_Gym_EventScript_MoveLeft2
	call_if_eq VAR_TEMP_1, 9, OlivineCity_Gym_EventScript_MoveLeft1
	call_if_eq VAR_TEMP_1, 10, OlivineCity_Gym_EventScript_MoveLeft0
	turnobject LOCALID_PLAYER, DIR_EAST
	msgbox OlivineCity_Gym_Text_Gent, MSGBOX_DEFAULT
	closemessage
	setvar VAR_OLIVINE_CITY_STATE, 6
	release
	end

OlivineCity_Gym_EventScript_MoveLeft0::
	turnobject VAR_TEMP_0, DIR_WEST
	return

OlivineCity_Gym_EventScript_MoveLeft1::
	applymovement VAR_TEMP_0, Common_Movement_WalkLeft
	waitmovement 0
	return

OlivineCity_Gym_EventScript_MoveLeft2::
	applymovement VAR_TEMP_0, Common_Movement_WalkLeft
	waitmovement 0
	applymovement VAR_TEMP_0, Common_Movement_WalkLeft
	waitmovement 0
	return

OlivineCity_Gym_EventScript_MoveLeft3::
	applymovement VAR_TEMP_0, Common_Movement_WalkLeft
	waitmovement 0
	applymovement VAR_TEMP_0, Common_Movement_WalkLeft
	waitmovement 0
	applymovement VAR_TEMP_0, Common_Movement_WalkLeft
	waitmovement 0
	return

OlivineCity_Gym_EventScript_MoveLeft4::
	applymovement VAR_TEMP_0, Common_Movement_WalkLeft
	waitmovement 0
	applymovement VAR_TEMP_0, Common_Movement_WalkLeft
	waitmovement 0
	applymovement VAR_TEMP_0, Common_Movement_WalkLeft
	waitmovement 0
	applymovement VAR_TEMP_0, Common_Movement_WalkLeft
	waitmovement 0
	return

OlivineCity_Gym_Text_Gent:
	.string "I knew you'd come here.\p"
	.string "Thank you for helping the Arena\n"
	.string "Leiter,\n"
	.string "but battle is a separate matter.\p"
	.string "Go for it!$"

OlivineCity_Gym_Text_Gent2:
	.string "Impressive!\n"
	.string "You should continue your journey to\n"
	.string "different places.\p"
	.string "Since you can use Surfer, why don't\n"
	.string "you try it on the See des Zorns?$"

OlivineCity_Gym_EventScript_Lass::
	lock
	faceplayer
	goto_if_set FLAG_DEFEATED_OLIVINE_CITY_GYM, OlivineCity_Gym_EventScript_Lass2
	msgbox OlivineCity_Gym_Text_Lass, MSGBOX_DEFAULT
	closemessage
	release
	end

OlivineCity_Gym_EventScript_Lass2::
	msgbox OlivineCity_Gym_Text_Lass2, MSGBOX_DEFAULT
	closemessage
	release
	end

OlivineCity_Gym_TriggerRow2::
	lock
	setvar VAR_TEMP_0, LOCALID_OLIVINE_CITY_GYM_NPC2
	playse SE_PIN
	applymovement VAR_TEMP_0, Common_Movement_ExclamationMark
	delay 60
	getplayerxy VAR_TEMP_1, VAR_TEMP_2
	call_if_eq VAR_TEMP_1, 6, OlivineCity_Gym_EventScript_MoveRight0
	call_if_eq VAR_TEMP_1, 7, OlivineCity_Gym_EventScript_MoveRight1
	call_if_eq VAR_TEMP_1, 8, OlivineCity_Gym_EventScript_MoveRight2
	call_if_eq VAR_TEMP_1, 9, OlivineCity_Gym_EventScript_MoveRight3
	call_if_eq VAR_TEMP_1, 10, OlivineCity_Gym_EventScript_MoveRight4
	turnobject LOCALID_PLAYER, DIR_WEST
	msgbox OlivineCity_Gym_Text_Lass, MSGBOX_DEFAULT
	closemessage
	setvar VAR_OLIVINE_CITY_STATE, 7
	release
	end

OlivineCity_Gym_EventScript_MoveRight0::
	turnobject VAR_TEMP_0, DIR_EAST
	return

OlivineCity_Gym_EventScript_MoveRight1::
	applymovement VAR_TEMP_0, Common_Movement_WalkRight
	waitmovement 0
	return

OlivineCity_Gym_EventScript_MoveRight2::
	applymovement VAR_TEMP_0, Common_Movement_WalkRight
	waitmovement 0
	applymovement VAR_TEMP_0, Common_Movement_WalkRight
	waitmovement 0
	return

OlivineCity_Gym_EventScript_MoveRight3::
	applymovement VAR_TEMP_0, Common_Movement_WalkRight
	waitmovement 0
	applymovement VAR_TEMP_0, Common_Movement_WalkRight
	waitmovement 0
	applymovement VAR_TEMP_0, Common_Movement_WalkRight
	waitmovement 0
	return

OlivineCity_Gym_EventScript_MoveRight4::
	applymovement VAR_TEMP_0, Common_Movement_WalkRight
	waitmovement 0
	applymovement VAR_TEMP_0, Common_Movement_WalkRight
	waitmovement 0
	applymovement VAR_TEMP_0, Common_Movement_WalkRight
	waitmovement 0
	applymovement VAR_TEMP_0, Common_Movement_WalkRight
	waitmovement 0
	return

OlivineCity_Gym_Text_Lass:
	.string "Kicher...\n"
	.string "Ich weiß, wie fähig du bist,\n"
	.string "beim LEUCHTTURM warst du Klasse!\p"
	.string "Zeig Jasmin deine Stärke!\n"
	.string "Viel Glück!$"

OlivineCity_Gym_Text_Lass2:
	.string "Du bist wirklich toll...\n"
	.string "Strebe noch höher, du hast\n"
	.string "so viel Potenzial.\p"
	.string "Warst du schon in Mahagonia?$"

OlivineCity_Gym_EventScript_GymGuide::
	lock
	faceplayer
	goto_if_lt VAR_OLIVINE_CITY_STATE, 5, OlivineCity_Gym_EventScript_GymGuideSick
	goto_if_set FLAG_DEFEATED_OLIVINE_CITY_GYM, OlivineCity_Gym_EventScript_GymGuideAfter
	msgbox OlivineCity_Gym_Text_GymGuideText, MSGBOX_DEFAULT
	closemessage
	release
	end

OlivineCity_Gym_EventScript_GymGuideSick::
	msgbox OlivineCity_Gym_Text_GymGuidePreText, MSGBOX_DEFAULT
	closemessage
	release
	end

OlivineCity_Gym_EventScript_GymGuideAfter::
	msgbox OlivineCity_Gym_Text_GymGuideWinText, MSGBOX_DEFAULT
	closemessage
	release
	end

OlivineCity_Gym_Text_GymGuideText:
	.string "JASMIN setzt den\n"
	.string "neu entdeckten Typ Stahl ein.\p"
	.string "Ich weiß nicht viel darüber.$"

OlivineCity_Gym_Text_GymGuideWinText:
	.string "Das war großartig!\p"
	.string "Der Typ Stahl, was?\p"
	.string "Das war eine un-\n"
	.string "heimliche Begegnung der unbekannten\l"
	.string "Art.$"

OlivineCity_Gym_Text_GymGuidePreText:
	.string "JASMIN, die ARENALEITERIN,\n"
	.string "ist im LEUCHTTURM.\p"
	.string "Sie kümmert sich\n"
	.string "um ein krankes Pokémon.\p"
	.string "Ein starker Trainer\n"
	.string "muss auch Mitgefühl zeigen.$"

OlivineCity_Gym_EventScript_Jasmine::
	lock
	faceplayer
	goto_if_set FLAG_DEFEATED_OLIVINE_CITY_GYM, OlivineCity_Gym_EventScript_Jasmine_Defeated
	msgbox OlivineCity_Gym_Text_JasmineSteelTypeIntro, MSGBOX_DEFAULT
	goto_if_set FLAG_DEFEATED_CIANWOOD_GYM, OlivineCity_Gym_EventScript_CianwoodCheckMahog
	goto_if_set FLAG_DEFEATED_MAHOGANY_TOWN_GYM, OlivineCity_Gym_EventScript_MahogCheckCianwood
	goto OlivineCity_Gym_EventScript_Jasmine_Battle1

OlivineCity_Gym_EventScript_JasmineVictory::
	message OlivineCity_Gym_Text_ReceivedMineralBadge
	waitmessage
	call Common_EventScript_PlayGymBadgeFanfare
	msgbox OlivineCity_Gym_Text_JasmineBadgeSpeech, MSGBOX_DEFAULT
	setflag FLAG_BADGE06_GET
	setflag FLAG_DEFEATED_OLIVINE_CITY_GYM
	addvar VAR_NUM_BADGES, 1
	setvar VAR_0x8008, 6
	call Common_EventScript_SetGymTrainers
	giveitem ITEM_TM_IRON_TAIL
	msgbox OlivineCity_Gym_Text_JasmineIronTailSpeech, MSGBOX_DEFAULT
	setvar VAR_OLIVINE_CITY_STATE, 8
	closemessage
	release
	end

OlivineCity_Gym_EventScript_CianwoodCheckMahog::
	goto_if_set FLAG_DEFEATED_MAHOGANY_TOWN_GYM, OlivineCity_Gym_EventScript_Jasmine_Battle3
	goto OlivineCity_Gym_EventScript_Jasmine_Battle2

OlivineCity_Gym_EventScript_MahogCheckCianwood::
	goto_if_set FLAG_DEFEATED_CIANWOOD_GYM, OlivineCity_Gym_EventScript_Jasmine_Battle3
	goto OlivineCity_Gym_EventScript_Jasmine_Battle2
	
OlivineCity_Gym_EventScript_Jasmine_Battle1::
	trainerbattle_no_intro TRAINER_JASMINE_1, OlivineCity_Gym_Text_JasmineBetterTrainer
	goto OlivineCity_Gym_EventScript_JasmineVictory

OlivineCity_Gym_EventScript_Jasmine_Battle2::
	trainerbattle_no_intro TRAINER_JASMINE_1_2, OlivineCity_Gym_Text_JasmineBetterTrainer
	goto OlivineCity_Gym_EventScript_JasmineVictory

OlivineCity_Gym_EventScript_Jasmine_Battle3::
	trainerbattle_no_intro TRAINER_JASMINE_1_3, OlivineCity_Gym_Text_JasmineBetterTrainer
	goto OlivineCity_Gym_EventScript_JasmineVictory

OlivineCity_Gym_EventScript_Jasmine_Defeated::
	msgbox OlivineCity_Gym_Text_JasmineGoodLuck, MSGBOX_DEFAULT
	closemessage
	release
	end


OlivineCity_Gym_Text_JasmineSteelTypeIntro:
	.string "…Danke für deine Hilfe am\n"
	.string "LEUCHTTURM…\p"
	.string "Aber das hier ist anders.\n"
	.string "Darf ich mich vorstellen?\p"
	.string "Ich bin Jasmin, Arenaleiterin.\n"
	.string "Ich nutze den Stahl-Typ.\p"
	.string "…Kennst du den Stahl-Typ?\p"
	.string "Er wurde erst kürzlich entdeckt.\p"
	.string "…Ähm… Soll ich anfangen?$"

OlivineCity_Gym_Text_JasmineBetterTrainer:
	.string "…Du bist ein besserer Trainer\n"
	.string "als ich, in Können und Herz.\p"
	.string "Nach den Regeln der LIGA\n"
	.string "überreiche ich dir diesen Orden.$"

OlivineCity_Gym_Text_ReceivedMineralBadge:
	.string "{PLAYER} erhielt MINERALORDEN.$"

OlivineCity_Gym_Text_JasmineBadgeSpeech:
	.string "MINERALORDEN erhöht die\n"
	.string "SPEZIAL-VERTEIDIGUNG von Pokémon.\p"
	.string "…Ähm… Bitte nimm dies auch…$"

OlivineCity_Gym_Text_JasmineIronTailSpeech:
	.string "…Du kannst damit TM lehren:\n"
	.string "EISENSCHWEIF.$"

OlivineCity_Gym_Text_JasmineGoodLuck:
	.string "Ähm… Ich weiß nicht, wie ich\n"
	.string "es sagen soll, aber viel Glück…$"

OlivineCity_Gym_Text_JasmineRematchText:
	.string "…Glückwunsch, JOHTO CHAMPION.\p"
	.string "Du bist so stark geworden…\p"
	.string "Ich frage mich, ob ich mich\n"
	.string "verbessert habe.\p"
	.string "Willst du es testen?\p"
	.string "Willst du ein Rematch mit mir?$"

OlivineCity_Gym_Text_JasmineRematchDefeatText:
	.string "…Du bist ein besserer Trainer\n"
	.string "als ich, in Können und Herz.$"

OlivineCity_Gym_EventScript_Statue::
	lock
	goto_if_set FLAG_DEFEATED_OLIVINE_CITY_GYM, OlivineCity_Gym_EventScript_Statue2
	msgbox OlivineCity_Gym_Text_GymStatue, MSGBOX_DEFAULT
	closemessage
	release
	end

OlivineCity_Gym_EventScript_Statue2::
	msgbox OlivineCity_Gym_Text_GymStatueCertified, MSGBOX_DEFAULT
	closemessage
	release
	end

OlivineCity_Gym_Text_GymStatue:
	.string "Oliviana City Pokémon Arena$"

OlivineCity_Gym_Text_GymStatueCertified:
	.string "Oliviana City Pokémon Arena\p"
	.string "Jasmin's zertifizierte Trainer:\n"
	.string "{PLAYER}$"
