.set LOCALID_GOLDENROD_UNDERGROUND_KIMONO, 12

GoldenrodCity_UndergroundTunnel_hns_MapScripts::
	map_script MAP_SCRIPT_ON_LOAD, GoldenrodCity_UndergroundTunnel_OnLoad
	.byte 0

GoldenrodCity_UndergroundTunnel_OnLoad::
	goto GoldenrodCity_UndergroundTunnel_MapScript_TryOpenDoor
	end
	
GoldenrodCity_UndergroundTunnel_EventScript_KimonoTriggerBot::
	lock
	playbgm MUS_HG_KIMONO_GIRL, TRUE
	applymovement LOCALID_GOLDENROD_UNDERGROUND_KIMONO, GoldenrodCity_UndergroundTunnel_Movement_Kimono_WalkToPlayerBot
	waitmovement 0
	msgbox GoldenrodCity_UndergroundTunnel_Text_Kimono1, MSGBOX_DEFAULT
	closemessage
	playse SE_PIN
	applymovement LOCALID_GOLDENROD_UNDERGROUND_KIMONO, Common_Movement_ExclamationMark
	delay 60
	msgbox GoldenrodCity_UndergroundTunnel_Text_Kimono2, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_GOLDENROD_UNDERGROUND_KIMONO, Common_Movement_WalkUp
	waitmovement 0
	applymovement LOCALID_GOLDENROD_UNDERGROUND_KIMONO, GoldenrodCity_UndergroundTunnel_Movement_Kimono_Leave1
	waitmovement 0
	playse SE_M_PETAL_DANCE
	applymovement LOCALID_GOLDENROD_UNDERGROUND_KIMONO, GoldenrodCity_UndergroundTunnel_Movement_Kimono_Spin
	waitmovement 0
	applymovement LOCALID_GOLDENROD_UNDERGROUND_KIMONO, GoldenrodCity_UndergroundTunnel_Movement_Kimono_Leave2
	waitmovement 0
	setflag FLAG_HIDE_GOLDENROD_UNDERGROUND_KIMONO
	removeobject LOCALID_GOLDENROD_UNDERGROUND_KIMONO
	fadedefaultbgm
	setvar VAR_GOLDENROD_CITY_STATE, 8
	end

GoldenrodCity_UndergroundTunnel_EventScript_KimonoTriggerTop::
	lock
	playbgm MUS_HG_KIMONO_GIRL, TRUE
	applymovement LOCALID_GOLDENROD_UNDERGROUND_KIMONO, GoldenrodCity_UndergroundTunnel_Movement_Kimono_WalkToPlayerTop
	waitmovement 0
	msgbox GoldenrodCity_UndergroundTunnel_Text_Kimono1, MSGBOX_DEFAULT
	closemessage
	playse SE_PIN
	applymovement LOCALID_GOLDENROD_UNDERGROUND_KIMONO, Common_Movement_ExclamationMark
	delay 60
	msgbox GoldenrodCity_UndergroundTunnel_Text_Kimono2, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_GOLDENROD_UNDERGROUND_KIMONO, Common_Movement_WalkDown
	waitmovement 0
	applymovement LOCALID_GOLDENROD_UNDERGROUND_KIMONO, GoldenrodCity_UndergroundTunnel_Movement_Kimono_Leave1
	waitmovement 0
	playse SE_M_PETAL_DANCE
	applymovement LOCALID_GOLDENROD_UNDERGROUND_KIMONO, GoldenrodCity_UndergroundTunnel_Movement_Kimono_Spin
	waitmovement 0
	applymovement LOCALID_GOLDENROD_UNDERGROUND_KIMONO, GoldenrodCity_UndergroundTunnel_Movement_Kimono_Leave2
	waitmovement 0
	setflag FLAG_HIDE_GOLDENROD_UNDERGROUND_KIMONO
	removeobject LOCALID_GOLDENROD_UNDERGROUND_KIMONO
	fadedefaultbgm
	setvar VAR_GOLDENROD_CITY_STATE, 8
	end


GoldenrodCity_UndergroundTunnel_Movement_Kimono_WalkToPlayerBot:
	walk_left
	walk_left
	walk_left
	walk_left
	step_end

GoldenrodCity_UndergroundTunnel_Movement_Kimono_WalkToPlayerTop:
	walk_up
	walk_left
	walk_left
	walk_left
	walk_left
	step_end

GoldenrodCity_UndergroundTunnel_Movement_Kimono_Leave1:
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	step_end

GoldenrodCity_UndergroundTunnel_Movement_Kimono_Spin:
	face_down
	face_right
	face_up
	face_left
	face_down
	face_right
	face_up
	step_end

GoldenrodCity_UndergroundTunnel_Movement_Kimono_Leave2:
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	step_end


GoldenrodCity_UndergroundTunnel_Text_Kimono1:
	.string "Team Rocket in schwarzen Anzügen\n"
	.string "laufen hier überall herum…\p"
	.string "Ich fragte mich, was los ist.\n"
	.string "Also hast du TEAM ROCKET bekämpft?\p"
	.string "Beeindruckend!\p"
	.string "Du könntest es sogar mit einem\n"
	.string "legendären POKéMON aufnehmen…$"

GoldenrodCity_UndergroundTunnel_Text_Kimono2:
	.string "Hahaha! Egal.\n"
	.string "Ich muss jetzt gehen.$"

GoldenrodUnderground_EventScript_Eric::
	trainerbattle_single TRAINER_ERIC GoldenrodUnderground_Text_SupernerdEricSeen, GoldenrodUnderground_Text_SupernerdEricBeaten
	msgbox GoldenrodUnderground_Text_SupernerdEricAfterBattle, MSGBOX_AUTOCLOSE
	end

GoldenrodUnderground_EventScript_Teru::
	trainerbattle_single TRAINER_TERU GoldenrodUnderground_Text_SupernerdTeruSeen, GoldenrodUnderground_Text_SupernerdTeruBeaten
	msgbox GoldenrodUnderground_Text_SupernerdTeruAfterBattle, MSGBOX_AUTOCLOSE
	end

GoldenrodUnderground_EventScript_Issac::
	trainerbattle_single TRAINER_ISSAC GoldenrodUnderground_Text_PokemaniacIssacSeen, GoldenrodUnderground_Text_PokemaniacIssacBeaten
	msgbox GoldenrodUnderground_Text_PokemaniacIssacAfterBattle, MSGBOX_AUTOCLOSE
	end

GoldenrodUnderground_EventScript_Donald::
	trainerbattle_single TRAINER_DONALD GoldenrodUnderground_Text_PokemaniacDonaldSeen, GoldenrodUnderground_Text_PokemaniacDonaldBeaten
	msgbox GoldenrodUnderground_Text_PokemaniacDonaldAfterBattle, MSGBOX_AUTOCLOSE
	end

GoldenrodUnderground_EventScript_Brother_Haircut1::
	lock
	faceplayer
	goto_if_set FLAG_DAILY_HAIRCUT1_RECEIVED, GoldenrodUnderground_EventScript_Already_Got_Haircut1
	showmoneybox 0, 0
	msgbox GoldenrodUnderground_Text_OlderBrotherOffer, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, TRUE, GoldenrodUnderground_EventScript_Haircut1
	msgbox GoldenrodUnderground_Text_OlderBrotherThatsAShame, MSGBOX_DEFAULT
	hidemoneybox
	closemessage
	end

GoldenrodUnderground_EventScript_Haircut1::
	msgbox GoldenrodUnderground_Text_OlderBrotherAskWhich
	special ChoosePartyMon
	waitstate
	showmoneybox 0, 0
	lock
	faceplayer
	goto_if_ge VAR_0x8004, PARTY_SIZE, GoldenrodUnderground_EventScript_Declined_Haircut1
	specialvar VAR_RESULT, ScriptGetPartyMonSpecies
	goto_if_eq VAR_RESULT, SPECIES_EGG, GoldenrodUnderground_EventScript_Declined_Haircut1
	checkmoney 500, 0
	goto_if_eq VAR_RESULT, FALSE, GoldenrodUnderground_EventScript_NotEnough_Haircut1
	removemoney 500
	updatemoneybox 0
	playse SE_SHOP
	msgbox GoldenrodUnderground_Text_OlderBrotherWatchItBeautiful
	closemessage
	fadescreen FADE_TO_BLACK
	playfanfare MUS_HEAL
	waitfanfare
	special HaircutBrother1
	fadescreen FADE_FROM_BLACK
	special BufferMonNickname
	msgbox GoldenrodUnderground_Text_OlderBrotherAllDone
	hidemoneybox
	setflag FLAG_DAILY_HAIRCUT1_RECEIVED
	release
	end

GoldenrodUnderground_EventScript_Declined_Haircut1::
	msgbox GoldenrodUnderground_Text_OlderBrotherThatsAShame, MSGBOX_DEFAULT
	hidemoneybox
	closemessage
	release
	end

GoldenrodUnderground_EventScript_Already_Got_Haircut1::
	msgbox GoldenrodUnderground_Text_OlderBrotherOnePerDay, MSGBOX_DEFAULT
	closemessage
	release
	end

GoldenrodUnderground_EventScript_NotEnough_Haircut1::
	msgbox GoldenrodUnderground_Text_OlderBrotherNeedMoreMoney, MSGBOX_DEFAULT
	closemessage
	hidemoneybox
	release
	end


GoldenrodUnderground_EventScript_Brother_Haircut2::
	lock
	faceplayer
	goto_if_set FLAG_DAILY_HAIRCUT2_RECEIVED, GoldenrodUnderground_EventScript_Already_Got_Haircut2
	showmoneybox 0, 0
	msgbox GoldenrodUnderground_Text_YoungerBrotherOffer, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, TRUE, GoldenrodUnderground_EventScript_Haircut2
	msgbox GoldenrodUnderground_Text_YoungerBrotherDisappointed, MSGBOX_DEFAULT
	hidemoneybox
	closemessage
	end

GoldenrodUnderground_EventScript_Haircut2::
	msgbox GoldenrodUnderground_Text_YoungerBrotherAskWhich
	special ChoosePartyMon
	waitstate
	showmoneybox 0, 0
	lock
	faceplayer
	goto_if_ge VAR_0x8004, PARTY_SIZE, GoldenrodUnderground_EventScript_Declined_Haircut2
	specialvar VAR_RESULT, ScriptGetPartyMonSpecies
	goto_if_eq VAR_RESULT, SPECIES_EGG, GoldenrodUnderground_EventScript_Declined_Haircut2
	checkmoney 300, 0
	goto_if_eq VAR_RESULT, FALSE, GoldenrodUnderground_EventScript_NotEnough_Haircut2
	removemoney 300
	updatemoneybox 0
	playse SE_SHOP
	msgbox GoldenrodUnderground_Text_YoungerBrotherLookCool
	closemessage
	fadescreen FADE_TO_BLACK
	playfanfare MUS_HEAL
	waitfanfare
	special HaircutBrother1
	fadescreen FADE_FROM_BLACK
	special BufferMonNickname
	msgbox GoldenrodUnderground_Text_YoungerBrotherAllDone
	hidemoneybox
	setflag FLAG_DAILY_HAIRCUT2_RECEIVED
	release
	end

GoldenrodUnderground_EventScript_Declined_Haircut2::
	msgbox GoldenrodUnderground_Text_YoungerBrotherDisappointed, MSGBOX_DEFAULT
	hidemoneybox
	closemessage
	release
	end

GoldenrodUnderground_EventScript_Already_Got_Haircut2::
	msgbox GoldenrodUnderground_Text_YoungerBrotherOnePerDay, MSGBOX_DEFAULT
	closemessage
	release
	end

GoldenrodUnderground_EventScript_NotEnough_Haircut2::
	msgbox GoldenrodUnderground_Text_YoungerBrotherShortOnFunds, MSGBOX_DEFAULT
	closemessage
	hidemoneybox
	release
	end


GoldenrodCity_UndergroundTunnel_MapScript_TryOpenDoor::
	goto_if_set FLAG_UNLOCKED_GOLDENROD_UNDERGROUND_DOOR, GoldenrodCity_UndergroundTunnel_MapScript_OpenDoor
	end

GoldenrodCity_UndergroundTunnel_MapScript_OpenDoor::
	setmetatile 12, 10, 0x2DD, FALSE
	end

GoldenrodCity_UndergroundTunnel_EventScript_Door::
	lock
	goto_if_set FLAG_UNLOCKED_GOLDENROD_UNDERGROUND_DOOR, GoldenrodCity_UndergroundTunnel_EventScript_DoorAlreadyOpened
	checkitem ITEM_BASEMENT_KEY
	goto_if_eq VAR_RESULT, TRUE, GoldenrodCity_UndergroundTunnel_EventScript_OpenDoor
	msgbox GoldenrodUnderground_Text_DoorsLocked, MSGBOX_DEFAULT
	closemessage
	release
	end

GoldenrodCity_UndergroundTunnel_EventScript_OpenDoor::
	msgbox GoldenrodUnderground_Text_KeyOpenedDoor, MSGBOX_DEFAULT
	closemessage
	setflag FLAG_UNLOCKED_GOLDENROD_UNDERGROUND_DOOR
	setmetatile 12, 10, 0x2DD, FALSE
	playse SE_BANG
	special DrawWholeMapView
	waitse
	release
	end

GoldenrodCity_UndergroundTunnel_EventScript_DoorAlreadyOpened::
	msgbox GoldenrodUnderground_Text_DoorIsOpen, MSGBOX_DEFAULT
	closemessage
	release
	end


GoldenrodCity_UndergroundTunnel_EventScript_Item_CoinCase::
	finditem ITEM_COIN_CASE
	end

GoldenrodCity_UndergroundTunnel_EventScript_Item_SuperPotion::
	finditem ITEM_SUPER_POTION
	end

GoldenrodCity_UndergroundTunnel_EventScript_Item_ParalyzeHeal::
	finditem ITEM_PARALYZE_HEAL
	end

GoldenrodCity_UndergroundTunnel_EventScript_Item_Antidote::
	finditem ITEM_ANTIDOTE
	end

GoldenrodUnderground_HerbShop_EventScript_Clerk::
	lock
	faceplayer
	message GoldenrodUnderground_HerbShop_Text_WelcomeToHerbShop
	waitmessage
	pokemart GoldenrodUnderground_HerbShop_Pokemart
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	release
	end

	.align 2
GoldenrodUnderground_HerbShop_Pokemart:
	.2byte ITEM_ENERGY_POWDER
	.2byte ITEM_ENERGY_ROOT
	.2byte ITEM_HEAL_POWDER
	.2byte ITEM_REVIVAL_HERB
	pokemartlistend

GoldenrodUnderground_HerbShop_Text_WelcomeToHerbShop:
	.string "Willkommen im KRÄUTERLADEN!\n"
	.string "Wir haben wirksame und\l"
	.string "preiswerte Medizin!$"

GoldenrodUnderground_Text_YoungerBrotherOffer:
	.string "Willkommen im Pokémon-SALON!\p"
	.string "Ich bin der jüngere und\n"
	.string "preiswertere Coiffeur-Bruder.\p"
	.string "Ich verschönere dein Pokémon\n"
	.string "für nur ¥300.\p"
	.string "Also? Wie wär's?$"

GoldenrodUnderground_Text_YoungerBrotherAskWhich:
	.string "Welches Pokémon soll ich machen?$"

GoldenrodUnderground_Text_YoungerBrotherLookCool:
	.string "O.K.! Es wird cool aussehen!$"

GoldenrodUnderground_Text_YoungerBrotherAllDone:
	.string "Bitte schön! Fertig!$"

GoldenrodUnderground_Text_YoungerBrotherDisappointed:
	.string "Nein? Schade!$"

GoldenrodUnderground_Text_YoungerBrotherShortOnFunds:
	.string "Du hast nicht genügend Geld.$"

GoldenrodUnderground_Text_YoungerBrotherOnePerDay:
	.string "Ich mache nur einen Haarschnitt\n"
	.string "pro Tag; für heute bin ich fertig.$"

GoldenrodUnderground_Text_OlderBrotherOffer:
	.string "Willkommen!\p"
	.string "Ich leite den Pokémon-SALON!\p"
	.string "Ich bin der ältere und bessere\n"
	.string "Coiffeur-Bruder.\p"
	.string "Ich verschönere dein Pokémon\n"
	.string "für nur ¥500.\p"
	.string "Soll ich anfangen?$"

GoldenrodUnderground_Text_OlderBrotherAskWhich:
	.string "Bei welchem Pokémon soll ich\n"
	.string "Hand anlegen?$"

GoldenrodUnderground_Text_OlderBrotherWatchItBeautiful:
	.string "O.K.! Sieh her, wie schön es wird!$"

GoldenrodUnderground_Text_OlderBrotherAllDone:
	.string "Hier! Fertig!$"

GoldenrodUnderground_Text_OlderBrotherThatsAShame:
	.string "Ist das wahr? Schade!$"

GoldenrodUnderground_Text_OlderBrotherNeedMoreMoney:
	.string "Du hast nicht genügend Geld.$"

GoldenrodUnderground_Text_OlderBrotherOnePerDay:
	.string "Ich mache nur einen Haarschnitt\n"
	.string "pro Tag; für heute bin ich fertig.$"

GoldenrodUnderground_Text_SupernerdEricSeen:
	.string "Ich wurde aus der SPIELHALLE\n"
	.string "geworfen.\p"
	.string "Ich wollte mit Pokémon betrügen…$"

GoldenrodUnderground_Text_SupernerdEricBeaten:
	.string "…Grummel…$"

GoldenrodUnderground_Text_SupernerdEricAfterBattle:
	.string "Ich muss wohl fair spielen…$"

GoldenrodUnderground_Text_SupernerdTeruSeen:
	.string "Denkst du bei Kämpfen an Typen?\p"
	.string "Wenn du deine Vorteile kennst,\n"
	.string "wirst du besser kämpfen.$"

GoldenrodUnderground_Text_SupernerdTeruBeaten:
	.string "Autsch, autsch, autsch!$"

GoldenrodUnderground_Text_SupernerdTeruAfterBattle:
	.string "Ich kenne die Typ-Vorteile.\p"
	.string "Aber ich nutze nur einen Typ.$"

GoldenrodUnderground_Text_PokemaniacIssacSeen:
	.string "Mein Pokémon hat einen Haarschnitt!\p"
	.string "Ich zeige dir, wie stark es ist!$"

GoldenrodUnderground_Text_PokemaniacIssacBeaten:
	.string "Aiyeeee!$"

GoldenrodUnderground_Text_PokemaniacIssacAfterBattle:
	.string "Pokémon mögen dich mehr, wenn\n"
	.string "du ihnen Haarschnitte gibst.$"

GoldenrodUnderground_Text_PokemaniacDonaldSeen:
	.string "Ich glaube, du hast seltene Pokémon\n"
	.string "bei dir.\p"
	.string "Zeig sie mir!$"

GoldenrodUnderground_Text_PokemaniacDonaldBeaten:
	.string "Gaah! Ich verlor! Wie ärgerlich!$"

GoldenrodUnderground_Text_PokemaniacDonaldAfterBattle:
	.string "Gestern Abend bei der BIKE SHOP\n"
	.string "fühlte ich mich beobachtet…$"

GoldenrodUnderground_Text_PokemaniacDonaldAfterBattleOld:
	.string "Machst du ein POKéDEX? Tipp:\p"
	.string "Der Wanderer auf ROUTE 33,\n"
	.string "TOM, ist nett.\p"
	.string "Er ruft dich, wenn er seltene\n"
	.string "Pokémon sieht.$"

GoldenrodUnderground_Text_DoorsLocked:
	.string "Die Tür ist verschlossen…$"

GoldenrodUnderground_Text_DoorIsOpen:
	.string "Die Tür ist entriegelt.$"

GoldenrodUnderground_Text_KeyOpenedDoor:
	.string "Mit dem KELLER-\n"
	.string "ÖFFNER wird die Tür entriegelt.$"

GoldenrodUnderground_Text_NoEntry:
	.string "BIS HIERHER UND NICHT WEITER$"
