PewterCity_House2_hns_MapScripts::
	.byte 0

PewterCity_House2_EventScript_Gramps::
	msgbox PewterCity_House2_Text_Gramps, MSGBOX_NPC
	end

PewterCity_House2_Text_Gramps:
	.string "Oh, du bist den\n"
	.string "ganzen Weg  von JOHTO bis hierher\n"
	.string "gekommen?\p"
	.string "Das weckt Erinnerungen. Als\p"
	.string "ich noch jung war,\n"
	.string "habe ich in JOHTO oft trainiert.\p"
	.string "Du erinnerst mich an mich\p"
	.string "selbst als junger Mann.\p"
	.string "Hier. Ich möchte,\n"
	.string "dass du dieses Item, das ich in JOHTO\l"
	.string "fand, behältst.$"

