LavenderTown_Mart_hns_MapScripts::
	.byte 0

LavenderTown_Mart_EventScript_Pokefan::
	msgbox LavenderMart_Text_PokefanM, MSGBOX_NPC
	end

LavenderTown_Mart_EventScript_Rocker::
	msgbox LavenderMart_Text_Rocker, MSGBOX_NPC
	end

LavenderMart_Text_PokefanM:
	.string "Es ist unabdingbar, SCHUTZ bei\p"
	.string "sich zu haben,\n"
	.string "wenn man Höhlen erkundet.\p"
	.string "Obwohl ich Höhlen sehr gerne\p"
	.string "erforsche, habe\n"
	.string "ich noch nicht alle erforscht.$"

LavenderMart_Text_Rocker:
	.string "Ich habe von einem Kunstschmied\p"
	.string "gehört, der maß-\n"
	.string "gefertigte Pokébälle in AZALEA\p"
	.string "in JOHTO her-\n"
	.string "stellt. Ich wünschte, ich hätte auch\l"
	.string "welche.$"
