VermilionCity_House2_hns_MapScripts::
	.byte 0

VermilionCity_House2_EventScript_PokefanF::
	msgbox VermilionCity_House2_Text_PokefanF, MSGBOX_NPC
	end

VermilionCity_House2_EventScript_Youngster::
	msgbox VermilionCity_House2_Text_Youngster, MSGBOX_NPC
	end

VermilionCity_House2_Text_PokefanF:
	.string "Kennst du den MAGNETZUG?\p"
	.string "Er fährt bis nach DUKATIA\n"
	.string "in JOHTO.$"

VermilionCity_House2_Text_Youngster:
	.string "Ich will nach SAFFRONIA,\n"
	.string "um den MAGNETZUG zu sehen.$"
