.set LOCALID_CIANWOOD_SUICUNE, 1
.set LOCALID_CIANWOOD_EUSINE, 2
.set LOCALID_CIANWOOD_CHUCKSWIFE, 6

CianwoodCity_hns_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, CianwoodCity_EventScript_CityEnter
	map_script MAP_SCRIPT_ON_FRAME_TABLE, CianwoodCity_OnFrame
	map_script MAP_SCRIPT_ON_LOAD, CianwoodCity_EventScript_InitializeSuicune
	.byte 0

CianwoodCity_RemoveEusine::
	setflag FLAG_HIDE_CIANWOOD_EUSINE
	end

CianwoodCity_OnFrame::
	map_script_2 VAR_GETFLY, 1, CianwoodCity_EventScript_Flytrigger
	.2byte 0

CianwoodCity_EventScript_CityEnter::
	setflag FLAG_VISITED_CIANWOOD_CITY
	goto_if_ge VAR_OLIVINE_CITY_STATE, 5, OlivineCity_MapScript_ClearWeather
	end

CianwoodCity_EventScript_InitializeSuicune::
	goto_if_ge VAR_SUICUNE_ENCOUNTERS, 2, CianwoodCity_EventScript_InitializeNothing
	clearflag FLAG_HIDE_CIANWOOD_SUICUNE
	setflag FLAG_HIDE_CIANWOOD_EUSINE
	setvar VAR_TEMP_0, 1
	end

CianwoodCity_EventScript_InitializeNothing::
	setvar VAR_TEMP_0, 1
	end

CianwoodCity_EventScript_Flytrigger::
	lock
	playse SE_PIN
	applymovement LOCALID_CIANWOOD_CHUCKSWIFE, Common_Movement_ExclamationMark
	delay 60
	applymovement LOCALID_CIANWOOD_CHUCKSWIFE, CianwoodCity_Movement_ChucksWife
	waitmovement 0
	msgbox CianwoodCity_Text_ChucksWifeGiveHM, MSGBOX_DEFAULT
	giveitem ITEM_HM_FLY
	setflag FLAG_RECEIVED_HM_FLY
	msgbox CianwoodCity_Text_ChucksWifeFlySpeech, MSGBOX_DEFAULT
	closemessage
	setvar VAR_GETFLY, 2
	release
	end

CianwoodCity_Movement_ChucksWife:
	walk_left
	walk_left
	walk_up
	walk_left
	face_up
	step_end

CianwoodCity_EventScript_Test::
	lock
	random 2
	call_if_eq VAR_RESULT, 1, EventScript_RockSmashHeartscale
	release
	end

CianwoodCity_EventScript_ChucksWife::
	lock
	faceplayer
	checkitem ITEM_HM_FLY
	goto_if_eq VAR_RESULT, TRUE, CianwoodCity_EventScript_ChucksWifeAlreadyHasFly
	msgbox CianwoodCity_Text_ChucksWifeEasierToFly, MSGBOX_DEFAULT
	goto_if_set FLAG_BADGE05_GET, CianwoodCity_EventScript_ChucksWifeGiveFly
	msgbox CianwoodCity_Text_ChucksWifeBeatChuck, MSGBOX_DEFAULT
	closemessage
	release
	end

CianwoodCity_EventScript_ChucksWifeGiveFly::
	msgbox CianwoodCity_Text_ChucksWifeGiveHM, MSGBOX_DEFAULT
	giveitem ITEM_HM_FLY
	setflag FLAG_RECEIVED_HM_FLY
	msgbox CianwoodCity_Text_ChucksWifeFlySpeech, MSGBOX_DEFAULT
	closemessage
	release
	end

CianwoodCity_EventScript_ChucksWifeAlreadyHasFly::
	msgbox CianwoodCity_Text_ChucksWifeChubby, MSGBOX_DEFAULT
	closemessage
	release
	end

CianwoodCity_Text_ChucksWifeEasierToFly:
	.string "Du bist über das Meer hierher\n"
	.string "gekommen?\p"
	.string "Das muss hart gewesen sein.\p"
	.string "Es wäre viel einfacher, wenn dein\n"
	.string "Pokémon Fliegen könnte...$"

CianwoodCity_Text_ChucksWifeBeatChuck:
	.string "Aber du kannst Fliegen ohne den\n"
	.string "Orden dieser Stadt nicht\n"
	.string "einsetzen.\p"
	.string "Wenn du den Arenaleiter hier\n"
	.string "besiegst, komm zu mir.\p"
	.string "Ich habe ein schönes Geschenk\n"
	.string "für dich.$"

CianwoodCity_Text_ChucksWifeGiveHM:
	.string "Das ist der Orden von Anemonia-City!\p"
	.string "Dann solltest du diese VM haben.$"

CianwoodCity_Text_ChucksWifeFlySpeech:
	.string "Bringe deinem Pokémon Fliegen bei.\p"
	.string "Du kannst dann sofort zu jedem Ort\n"
	.string "Fliegen, den du bereits besucht hast.$"

CianwoodCity_Text_ChucksWifeChubby:
	.string "Mein Mann hat gegen dich verloren,\n"
	.string "also muss er härter trainieren.\p"
	.string "Gut so, er wurde nämlich ein\n"
	.string "bisschen pummelig.$"

CianwoodCity_EventScript_Youngster::
	lock
	faceplayer
	msgbox CianwoodCity_Text_Youngster, MSGBOX_DEFAULT
	closemessage
	release
	end

CianwoodCity_Text_Youngster:
	.string "Mit Fliegen kannst du sofort zurück\n"
	.string "nach Oliviana City.$"

CianwoodCity_EventScript_PokefanM::
	lock
	faceplayer
	msgbox CianwoodCity_Text_PokefanM, MSGBOX_DEFAULT
	closemessage
	release
	end

CianwoodCity_Text_PokefanM:
	.string "Felsen nördlich der Stadt können\n"
	.string "zertrümmert werden.\p"
	.string "Manchmal verbirgt sich etwas darin.\p"
	.string "Dein Pokémon kann ZERTRÜMMERER\n"
	.string "einsetzen, um sie zu zerbrechen.$"

CianwoodCity_EventScript_Lass::
	lock
	faceplayer
	msgbox CianwoodCity_Text_Lass, MSGBOX_DEFAULT
	closemessage
	release
	end

CianwoodCity_Text_Lass:
	.string "Hartwig, der Arenaleiter, übt mit\n"
	.string "seinen\l"
	.string "Kampf-Pokémon mit bloßen Händen!$"

CianwoodCity_EventScript_SuicuneTrigger::
	lock
	playmoncry SPECIES_SUICUNE, CRY_MODE_NORMAL
	applymovement LOCALID_CIANWOOD_SUICUNE, CianwoodCity_Movement_Suicune1
	playse SE_LEDGE
	waitse
	playse SE_LEDGE
	waitse
	waitmovement 0
	waitmoncry
	playse SE_PIN
	applymovement LOCALID_PLAYER, Common_Movement_ExclamationMark
	delay 60
	applymovement LOCALID_CIANWOOD_SUICUNE, CianwoodCity_Movement_Suicune2
	playse SE_LEDGE
	delay 30
	playse SE_LEDGE
	delay 30
	playse SE_LEDGE
	delay 30
	waitmovement 0
	turnobject LOCALID_PLAYER, DIR_SOUTH
	playmoncry SPECIES_SUICUNE, CRY_MODE_NORMAL
	waitmoncry
	applymovement LOCALID_CIANWOOD_SUICUNE, CianwoodCity_Movement_Suicune3
	playse SE_LEDGE
	delay 30
	playse SE_LEDGE
	delay 30
	playse SE_LEDGE
	delay 30
	playse SE_LEDGE
	delay 30
	playse SE_LEDGE
	delay 30
	waitmovement 0
	delay 30
	playbgm MUS_HG_EUSINE, TRUE
	clearflag FLAG_HIDE_CIANWOOD_EUSINE
	addobject LOCALID_CIANWOOD_EUSINE
	applymovement LOCALID_CIANWOOD_EUSINE, CianwoodCity_Movement_Eusine1
	waitmovement 0
	delay 55
	applymovement LOCALID_CIANWOOD_EUSINE, CianwoodCity_Movement_Eusine2
	waitmovement 0 
	msgbox CianwoodCity_Text_EusineSuicune, MSGBOX_DEFAULT
	trainerbattle_no_intro TRAINER_EUSINE, CianwoodCity_Text_EusineBeaten
	playbgm MUS_HG_EUSINE, TRUE
	msgbox CianwoodCity_Text_EusineAfter, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_CIANWOOD_EUSINE, CianwoodCity_Movement_Eusine3
	waitmovement 0
	setflag FLAG_HIDE_CIANWOOD_EUSINE
	setflag FLAG_HIDE_CIANWOOD_SUICUNE
	removeobject LOCALID_CIANWOOD_SUICUNE
	removeobject LOCALID_CIANWOOD_EUSINE
	setvar VAR_SUICUNE_ENCOUNTERS, 2
	setvar VAR_CIANWOOD_CITY_STATE, 2
	fadedefaultbgm
	call_if_set FLAG_HIDE_ROUTE42_SUICUNE, CianwoodCity_EventScript_DoneJohtoSuicune
	release
	end

CianwoodCity_EventScript_DoneJohtoSuicune::
	setvar VAR_SUICUNE_ENCOUNTERS, 3
	return

CianwoodCity_Movement_Suicune1:
	jump_in_place_right_left
	jump_in_place_right_left
	face_down
	step_end

CianwoodCity_Movement_Suicune2:
	jump_down
	jump_2_down
	jump_right
	face_up
	step_end

CianwoodCity_Movement_Suicune3:
	jump_2_down
	jump_2_right
	jump_2_right
	jump_2_right
	jump_2_right
	jump_2_right
	step_end

CianwoodCity_Movement_Eusine1:
	walk_fast_up
	walk_fast_up
	walk_fast_up
	walk_fast_up
	face_right
	step_end

CianwoodCity_Movement_Eusine2:
	face_up
	walk_up
	walk_up
	step_end

CianwoodCity_Movement_Eusine3:
	face_down
	walk_fast_down
	walk_fast_down
	walk_fast_down
	walk_fast_down
	walk_fast_down
	walk_fast_down
	walk_fast_down
	step_end

CianwoodCity_Text_EusineSuicune:
	.string "Eusin: Yo, {PLAYER}.\p"
	.string "War das eben nicht Suicune?\p"
	.string "Ich habe es nur kurz gesehen, aber\n"
	.string "ich glaube, ich sah Suicune über die\l"
	.string "Wellen laufen.\p"
	.string "Suicune ist wunderschön und erhaben.\p"
	.string "Und es jagt mit unglaublicher\n"
	.string "Geschwindigkeit durch Städte und\n"
	.string "über Straßen.\p"
	.string "Es ist wunderbar…\p"
	.string "Ich möchte Suicune aus der Nähe\n"
	.string "sehen…\p"
	.string "Ich habe mich entschieden.\p"
	.string "Ich werde gegen dich kämpfen, um\n"
	.string "Suicunes Respekt zu verdienen!\p"
	.string "Los, {PLAYER}. Lass uns jetzt\n"
	.string "kämpfen!$"

CianwoodCity_Text_EusineBeaten:
	.string "Ich gebe es ungern zu, aber du hast\n"
	.string "gewonnen.$"

CianwoodCity_Text_EusineAfter:
	.string "Du bist unglaublich, {PLAYER}!\p"
	.string "Kein Wunder, dass Pokémon sich zu dir\n"
	.string "hingezogen fühlen.\p"
	.string "Jetzt verstehe ich es.\p"
	.string "Ich werde weiter nach Suicune suchen.\n"
	.string "\p"
	.string "Wir werden uns sicher wiedersehen.\p"
	.string "Bis dann!$"

CianwoodCity_EventScript_CitySign::
	lock
	msgbox CianwoodCity_Text_Sign, MSGBOX_SIGN
	closemessage
	release
	end

CianwoodCity_Text_Sign:
	.string "Anemonia City\p"
	.string "Ein Hafen in der rauen See$"

CianwoodCity_EventScript_GymSign::
	lock
	msgbox CianwoodCity_Text_GymSign, MSGBOX_SIGN
	closemessage
	release
	end

CianwoodCity_Text_GymSign:
	.string "Anemonia City Pokémon Arena\p"
	.string "Leiter: Hartwig\p"
	.string "Die Fäuste werden sprechen$"

CianwoodCity_EventScript_Pharmacy::
	lock
	msgbox CianwoodCity_Text_PharmacySign, MSGBOX_SIGN
	closemessage
	release
	end

CianwoodCity_Text_PharmacySign:
	.string "500 Jahre Tradition\p"
	.string "Anemonia City Apotheke\p"
	.string "Wir erwarten ihre Anfragen$"

CianwoodCity_EventScript_CaveSign::
	lock
	msgbox CianwoodCity_Text_Safari, MSGBOX_SIGN
	closemessage
	release
	end

CianwoodCity_EventScript_Engineer::
	lock
	faceplayer
	msgbox CianwoodCity_Text_Engineer, MSGBOX_DEFAULT
	closemessage
	release
	end

CianwoodCity_Text_Safari:
	.string "FELSSCHLUNDHÖHLE Weg zur Safari-Zone.$"

CianwoodCity_Text_Engineer:
	.string "Hier sind aktuell Bauarbeiten.\n"
	.string "Wir gestalten die neue Safari-Zone,\l"
	.string "du musst noch warten.$"
